(()=>{
'use strict';
const Q=window.QUESTION_BANK||[];
const PED=window.HOS_PEDAGOGY||{};
const FILL_BANK=PED.fillBank||{};
const ENHANCED_FILL_BANK=window.HOS_ENHANCED_FILL||{};
const JUDGE_CORRECTIONS=PED.judgeCorrections||{};
const SELECTION_REASONS=PED.selectionReasons||{};
const JUDGE_REASONS=PED.judgeReasons||{};
const OPTION_NOTES=PED.optionNotes||{};
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const STORE_KEY='shenrenliu_qbank_v1';
const STORE_SCHEMA_VERSION=2,BANK_VERSION='v2.2',VALID_IDS=new Set(Q.map(q=>q.id));
const DUPLICATE_GROUPS=[[63,121],[71,109],[101,450],[197,230],[203,281],[208,286],[225,245],[236,284],[244,287],[379,465],[384,466]];
const DUPLICATE_GROUP_BY_ID=Object.fromEntries(DUPLICATE_GROUPS.flatMap((ids,i)=>ids.map(id=>[id,`D${i+1}`])));
const emptyAggregate=()=>({totalExams:0,totalAnswers:0,totalCorrect:0,totalStudyMs:0,highestScore:0,recentScores:[],byType:{},byQuestion:{},byTag:{},weeks:{}});
const defaultStore={schemaVersion:STORE_SCHEMA_VERSION,favorites:[],wrong:{},mastery:{},reviewFlags:{},seen:{},learning:{},history:[],aggregateStats:emptyAggregate(),examRotation:{round:0,recent:[],usage:{},lastSeenRound:{}},settings:{theme:'light',watermark:'both',defaultFillRatio:15,shuffleOptions:true,confidenceRequired:false,lastBackup:0},lastSession:null};
let S=loadStore();
try{localStorage.setItem(STORE_KEY,JSON.stringify(S))}catch(e){}
let view='home', session=null, current=0, sourcePage=1, sourcePages=[];
let deferredInstallPrompt=null,timerTicker=null,saveDebounceTimer=null,backGuardReady=false,backExitArmed=false,backRearmTimer=null;

function freshDefaultStore(){return JSON.parse(JSON.stringify(defaultStore))}
function num(v,min=0,max=Number.MAX_SAFE_INTEGER){v=Number(v);return Number.isFinite(v)?Math.min(max,Math.max(min,v)):min}
function validIdList(v){return Array.isArray(v)?[...new Set(v.map(Number).filter(id=>VALID_IDS.has(id)))]:[]}
function safeKeyObject(v,mapper=x=>x){let out={};if(!v||typeof v!=='object'||Array.isArray(v))return out;for(const [k,x] of Object.entries(v)){let id=Number(k);if(VALID_IDS.has(id))out[id]=mapper(x,id)}return out}
function validatePaperItem(q,renderType,fillLevel){if(!q)return false;if(renderType==='fill')return ['standard','enhanced'].includes(fillLevel)&&isFillEligible(q,fillLevel);return ['single','multiple','judge'].includes(renderType)&&renderType===q.type}
function sanitizeSavedAnswer(q,renderType,raw){if(raw==null)return null;if(renderType==='fill'){if(typeof raw==='string')return raw;if(Array.isArray(raw)&&raw.every(x=>typeof x==='string'))return raw.join('、');return null}if(renderType==='multiple'){if(!Array.isArray(raw))return null;let out=[];for(const value of raw){if(typeof value!=='string')return null;let option=q.options.find(x=>cleanAns(x)===cleanAns(value));if(!option)return null;if(!out.includes(option))out.push(option)}return out}if(renderType==='single'||renderType==='judge'){if(typeof raw!=='string'||!raw)return null;return q.options.find(x=>cleanAns(x)===cleanAns(raw))||null}return null}
function sanitizeHistory(v){if(!Array.isArray(v))return [];return v.slice(0,50).map(x=>{x=x&&typeof x==='object'?x:{};let rawIds=Array.isArray(x.ids)?x.ids:[],rawTypes=Array.isArray(x.renderTypes)?x.renderTypes:[],rawLevels=Array.isArray(x.fillLevels)?x.fillLevels:[],seen=new Set(),tuples=[],paperDamaged=!!x.paperDamaged||(rawIds.length>0&&(rawTypes.length!==rawIds.length||rawLevels.length!==rawIds.length));for(let i=0;i<rawIds.length;i++){let id=Number(rawIds[i]),q=Q.find(z=>z.id===id),renderType=rawTypes[i],fillLevel=renderType==='fill'?rawLevels[i]:'standard';if(!VALID_IDS.has(id)||seen.has(id)||!validatePaperItem(q,renderType,fillLevel)){paperDamaged=true;continue}seen.add(id);let raw=Array.isArray(x.optionOrders?.[i])?x.optionOrders[i]:q.options,optionOrder=raw.length===q.options.length&&raw.every(o=>q.options.includes(o))&&new Set(raw).size===raw.length?[...raw]:[...q.options];tuples.push({id,renderType,fillLevel,optionOrder})}let ids=tuples.map(z=>z.id),renderTypes=tuples.map(z=>z.renderType),fillLevels=tuples.map(z=>z.fillLevel),optionOrders=tuples.map(z=>z.optionOrder);return {time:num(x.time,0),mode:String(x.mode||'模拟考试').slice(0,50),count:num(x.count,0,507),correct:num(x.correct,0,507),score:num(x.score,0,100),durationMs:num(x.durationMs,0,86400000),avgMs:num(x.avgMs,0,86400000),highCount:num(x.highCount,0,507),highIds:validIdList(x.highIds),typeTimes:x.typeTimes&&typeof x.typeTimes==='object'?Object.fromEntries(Object.entries(x.typeTimes).map(([k,n])=>[String(k).slice(0,20),num(n,0,86400000)])): {},questionTimes:Array.isArray(x.questionTimes)?x.questionTimes.slice(0,507).map(z=>({id:VALID_IDS.has(Number(z?.id))?Number(z.id):0,type:String(z?.type||'').slice(0,10),ms:num(z?.ms,0,86400000),correct:!!z?.correct,assisted:!!z?.assisted,confidence:['sure','hesitant','guess'].includes(z?.confidence)?z.confidence:''})).filter(z=>z.id):[],paperId:String(x.paperId||'').slice(0,80),paperDamaged,ids,renderTypes,fillLevels,optionOrders}})}
function sanitizeLastSession(x){if(!x||typeof x!=='object'||!['v2.1','v2.2'].includes(x.bankVersion)||x.kind!=='exam'||!Array.isArray(x.ids)||!x.ids.length||x.ids.length>507)return null;let ids=x.ids.map(Number);if(ids.some(id=>!VALID_IDS.has(id))||new Set(ids).size!==ids.length||!Array.isArray(x.renderTypes)||x.renderTypes.length!==ids.length||!Array.isArray(x.fillLevels)||x.fillLevels.length!==ids.length||!Array.isArray(x.answers)||x.answers.length!==ids.length)return null;let answers=[],orders=[];for(let i=0;i<ids.length;i++){let q=Q.find(z=>z.id===ids[i]),t=x.renderTypes[i],l=t==='fill'?x.fillLevels[i]:'standard';if(!validatePaperItem(q,t,l))return null;answers.push(sanitizeSavedAnswer(q,t,x.answers[i]));let raw=Array.isArray(x.optionOrders?.[i])?x.optionOrders[i]:q.options;if(raw.length!==q.options.length||raw.some(o=>!q.options.includes(o))||new Set(raw).size!==raw.length)raw=q.options;orders.push([...raw])}let rawTimes=Array.isArray(x.timeMs)?x.timeMs:[];return {...x,bankVersion:BANK_VERSION,ids,answers,optionOrders:orders,fillLevels:ids.map((_,i)=>x.renderTypes[i]==='fill'?x.fillLevels[i]:'standard'),current:Math.floor(num(x.current,0,ids.length-1)),timeMs:ids.map((_,i)=>num(rawTimes[i],0,86400000)),totalActiveMs:num(x.totalActiveMs,0,86400000),started:num(x.started,0),strict:!!x.strict,rotationRecorded:!!x.rotationRecorded,paperId:String(x.paperId||'').slice(0,80)}}
function schemaVersionOf(d){if(d.schemaVersion===undefined)return 1;if(typeof d.schemaVersion!=='number'||!Number.isInteger(d.schemaVersion)||d.schemaVersion<1)throw Error('备份版本字段不兼容');if(d.schemaVersion>STORE_SCHEMA_VERSION)throw Error('该备份来自更高版本，请先升级题库程序');return d.schemaVersion}
function sanitizeSettings(v,base){let d=v&&typeof v==='object'&&!Array.isArray(v)?v:{},ratios=[10,15,20,25],raw=num(d.defaultFillRatio??base.defaultFillRatio,0,30),defaultFillRatio=ratios.reduce((a,b)=>Math.abs(b-raw)<Math.abs(a-raw)?b:a,ratios[0]);return {theme:['light','dark'].includes(d.theme)?d.theme:base.theme,watermark:['both','cn','en','off'].includes(d.watermark)?d.watermark:base.watermark,defaultFillRatio,shuffleOptions:d.shuffleOptions!==false,confidenceRequired:!!d.confidenceRequired,lastBackup:num(d.lastBackup,0)}}
function sanitizeAggregate(v){let d=v&&typeof v==='object'&&!Array.isArray(v)?v:{},base=emptyAggregate(),safeStats=o=>o&&typeof o==='object'&&!Array.isArray(o)?o:{};return {...base,totalExams:num(d.totalExams,0,1e9),totalAnswers:num(d.totalAnswers,0,1e12),totalCorrect:num(d.totalCorrect,0,1e12),totalStudyMs:num(d.totalStudyMs,0,1e15),highestScore:num(d.highestScore,0,100),recentScores:Array.isArray(d.recentScores)?d.recentScores.slice(-20).map(x=>num(x,0,100)):[],byType:safeStats(d.byType),byQuestion:safeKeyObject(d.byQuestion,x=>({attempts:num(x?.attempts,0,1e9),correct:num(x?.correct,0,1e9),wrong:num(x?.wrong,0,1e9),totalMs:num(x?.totalMs,0,1e15)})),byTag:safeStats(d.byTag),weeks:safeStats(d.weeks)}}
function hydrateStore(raw={}){let base=freshDefaultStore(),d=raw&&typeof raw==='object'&&!Array.isArray(raw)?raw:{};schemaVersionOf(d);let recent=Array.isArray(d.examRotation?.recent)?d.examRotation.recent.slice(-10).map(validIdList):[];return {...base,schemaVersion:STORE_SCHEMA_VERSION,favorites:validIdList(d.favorites),wrong:safeKeyObject(d.wrong,x=>({count:num(x?.count??x?.wrongTotal,0,99999),wrongTotal:num(x?.wrongTotal??x?.count,0,99999),wrongStreak:num(x?.wrongStreak,0,9999),lastWrong:num(x?.lastWrong??x?.last,0),lastCorrect:num(x?.lastCorrect,0),independentCorrectStreak:num(x?.independentCorrectStreak,0,9999),assistedCorrect:num(x?.assistedCorrect,0,99999),recentResult:String(x?.recentResult||'').slice(0,24),corrected:!!x?.corrected})),mastery:safeKeyObject(d.mastery,x=>['mastered','fuzzy','new'].includes(x)?x:''),reviewFlags:safeKeyObject(d.reviewFlags,x=>num(x,0)),seen:safeKeyObject(d.seen,x=>num(x,0)),learning:safeKeyObject(d.learning,x=>({attempts:num(x?.attempts,0,99999),correct:num(x?.correct,0,99999),wrong:num(x?.wrong,0,99999),streak:num(x?.streak,0,9999),totalMs:num(x?.totalMs,0,1e12),timedAttempts:num(x?.timedAttempts,0,99999),assistedCorrect:num(x?.assistedCorrect,0,99999),lowConfidenceCorrect:num(x?.lowConfidenceCorrect,0,99999),totalExposure:num(x?.totalExposure,0,999999),regularExposure:num(x?.regularExposure,0,999999),fillExposure:num(x?.fillExposure,0,999999),lastSeenRound:num(x?.lastSeenRound,0,999999),last:num(x?.last,0),due:num(x?.due,0)})),history:sanitizeHistory(d.history),aggregateStats:sanitizeAggregate(d.aggregateStats),examRotation:{round:num(d.examRotation?.round,0,999999),recent,usage:safeKeyObject(d.examRotation?.usage,x=>num(x,0,999999)),lastSeenRound:safeKeyObject(d.examRotation?.lastSeenRound,x=>num(x,0,999999))},settings:sanitizeSettings(d.settings,base.settings),lastSession:sanitizeLastSession(d.lastSession)}}
function loadStore(){try{return hydrateStore(JSON.parse(localStorage.getItem(STORE_KEY)||'{}'))}catch(e){return freshDefaultStore()}}
function saveStore(){if(saveDebounceTimer){clearTimeout(saveDebounceTimer);saveDebounceTimer=null}try{localStorage.setItem(STORE_KEY,JSON.stringify(S))}catch(e){} updateWatermark();}
function queueSave(){if(saveDebounceTimer)clearTimeout(saveDebounceTimer);saveDebounceTimer=setTimeout(saveStore,350)}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function normalizeOcrText(v=''){let s=String(v);s=s.replace(/\(（/g,'（').replace(/）\)/g,'）').replace(/〔（/g,'（').replace(/〔/g,'（');s=s.replace(/（\s*）\s*[）)]/g,'（ ）').replace(/[（(]\s*（\s*）/g,'（ ）');s=s.replace(/([\u3400-\u9fff])\s+(?=[\u3400-\u9fff])/g,'$1').replace(/\s+([，。；：？！])/g,'$1');return s}
function displayText(v=''){return normalizeOcrText(v)}
function auditQuestionBank(){let errors=[],ids=new Set,allowed=new Set(['single','multiple','judge']),residue=/(正确答案|正确等完|正确等罕|正确到衬|正确从\s*#|\|\s*$|无估|牌斜|炸贴|翘边突(?!出)|用族|不期营|电亲|账短|周转条类|肥和|手棍|【|】)/;if(Q.length!==507)errors.push(`题目总数应为507，实际为${Q.length}`);for(const q of Q){if(!Number.isInteger(q.id)||ids.has(q.id))errors.push(`题号${q.id}重复或无效`);ids.add(q.id);if(!allowed.has(q.type))errors.push(`#${q.id}题型无效`);if(!q.stem||!Array.isArray(q.options)||!q.options.length||!Array.isArray(q.answers)||!q.answers.length)errors.push(`#${q.id}字段不完整`);if(q.type==='single'&&q.answers.length!==1)errors.push(`#${q.id}单选答案数不是1`);if(q.type==='judge'&&(q.answers.length!==1||!['对','错'].includes(q.answers[0])))errors.push(`#${q.id}判断答案异常`);if(q.answers.some(a=>!q.options.includes(a)))errors.push(`#${q.id}答案不在选项中`);if(new Set(q.options).size!==q.options.length)errors.push(`#${q.id}存在重复选项`);if(q.sourceAnswerCount!=null&&q.sourceAnswerCount!==q.answers.length)errors.push(`#${q.id}答案数与原图复核数不一致`);if([q.stem,...q.options].some(x=>residue.test(String(x))))errors.push(`#${q.id}仍含答案标记或OCR残字`);let pages=q.sourceImages||[q.sourceImage];if(!pages.length||pages.some(x=>!Number.isInteger(x)||x<1||x>111))errors.push(`#${q.id}原题页码异常`)}let locks={137:['针脚无歪斜'],142:['无翘边突出'],160:['与自己无关'],166:['锤子或撬棍'],200:['肥皂'],403:['矛盾'],434:['规定用途'],437:['不期望情况'],457:['电源上挂牌'],501:['账簿记录'],505:['周转箱类']};for(const [id,words] of Object.entries(locks)){let q=Q.find(x=>x.id===Number(id)),text=[q?.stem,...(q?.options||[])].join('');if(!q||words.some(w=>!text.includes(w)))errors.push(`#${id}复核文字锁异常`)}return errors}
const BANK_AUDIT_ERRORS=auditQuestionBank();
function blankCount(v=''){return (displayText(v).match(/[（(]\s*[）)]/g)||[]).length}
function fillEntry(q,level='standard'){if(!q)return null;return level==='enhanced'?(ENHANCED_FILL_BANK[q.id]||FILL_BANK[q.id]||null):(FILL_BANK[q.id]||null)}
function isFillEligible(q,level='standard'){return !!fillEntry(q,level)?.stem}
function questionAnswers(q,renderType=q.type,level='standard'){let entry=renderType==='fill'?fillEntry(q,level):null;return (entry?.answers||q.answers||[]).map(displayText)}
function auditFillBanks(){let errors=[],standardIds=Object.keys(FILL_BANK),full={...FILL_BANK,...ENHANCED_FILL_BANK};if(standardIds.length!==104)errors.push(`标准填空应为104题，实际为${standardIds.length}`);if(Object.keys(full).length!==198)errors.push(`增强填空应为198题，实际为${Object.keys(full).length}`);for(const [id,e] of Object.entries(full)){let q=Q.find(x=>x.id===Number(id)),answers=e.answers||q?.answers;if(!q)errors.push(`#${id}填空原题不存在`);if(!e.stem||!e.stem.includes('______'))errors.push(`#${id}填空题干异常`);if(!Array.isArray(answers)||!answers.length)errors.push(`#${id}填空答案缺失`);if(q?.type==='judge'&&answers?.some(x=>x==='对'||x==='错'))errors.push(`#${id}判断改填空仍使用对错答案`)}return errors}
const FILL_AUDIT_ERRORS=auditFillBanks();BANK_AUDIT_ERRORS.push(...FILL_AUDIT_ERRORS);
function rotationState(){S.examRotation=S.examRotation||{round:0,recent:[],usage:{},lastSeenRound:{}};S.examRotation.lastSeenRound=S.examRotation.lastSeenRound||{};return S.examRotation}
function duplicateKey(id){return DUPLICATE_GROUP_BY_ID[id]||`Q${id}`}
function rotationRanks(){let r=rotationState(),rounds=r.recent||[];return {r,recent10:rounds.slice(-10)}}
function learningPriority(q){let l=S.learning[q.id]||{},w=S.wrong[q.id]||{},now=Date.now(),attempts=l.attempts||0,accuracy=attempts?(l.correct||0)/attempts:0,avg=l.timedAttempts?l.totalMs/l.timedAttempts:0;return (w.wrongTotal||w.count||0)*18+(w.wrongStreak||0)*35+(l.assistedCorrect||0)*14+(l.lowConfidenceCorrect||0)*12+(avg>=30000?18:0)+(l.due&&l.due<=now?25:0)+(1-accuracy)*10}
function rankedCandidates(pool,balanced=false){let {r,recent10}=rotationRanks(),round=r.round||0;return pool.map(q=>{let used=num(r.usage[q.id],0),last=num(r.lastSeenRound[q.id],0),gap=last?round-last:999,recencyPenalty=last?Math.max(0,11-gap)*30:0,exposurePenalty=used*100,learn=balanced?learningPriority(q):0,random=Math.random();return {q,score:exposurePenalty+recencyPenalty-learn,random}}).sort((a,b)=>a.score-b.score||a.random-b.random)}
function coveragePick(pool,n,blocked=new Set(),balanced=false){let blockedGroups=new Set([...blocked].map(duplicateKey)),out=[];for(const x of rankedCandidates(pool.filter(q=>!blocked.has(q.id)),balanced)){let g=duplicateKey(x.q.id);if(blockedGroups.has(g))continue;out.push(x.q);blockedGroups.add(g);if(out.length>=n)break}return out}
function pickRealRegular(type,n,blocked){return coveragePick(Q.filter(q=>q.type===type),n,blocked)}
function recordExamRotation(items){let r=rotationState(),ids=[...new Set(items.map(x=>x.q.id))];r.round++;r.recent=[...(r.recent||[]),ids].slice(-10);for(const id of ids){r.usage[id]=(r.usage[id]||0)+1;r.lastSeenRound[id]=r.round;let l=S.learning[id]||(S.learning[id]={attempts:0,correct:0,wrong:0,streak:0,totalMs:0,timedAttempts:0,assistedCorrect:0,lowConfidenceCorrect:0,totalExposure:0,regularExposure:0,fillExposure:0,lastSeenRound:0,last:0,due:0});l.totalExposure++;let item=items.find(x=>x.q.id===id);if(item?.renderType==='fill')l.fillExposure++;else l.regularExposure++;l.lastSeenRound=r.round}saveStore()}
function typeName(t){return t==='single'?'单选题':t==='multiple'?'多选题':t==='judge'?'判断题':'填空题'}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function hashSeed(v){let h=2166136261;for(const c of String(v)){h^=c.charCodeAt(0);h=Math.imul(h,16777619)}return h>>>0}
function stableOptionOrder(q,seed){let a=[...q.options],state=hashSeed(`${seed}:${q.id}`);for(let i=a.length-1;i>0;i--){state=(Math.imul(state,1664525)+1013904223)>>>0;let j=state%(i+1);[a[i],a[j]]=[a[j],a[i]]}return a}
function applyOptionOrders(items,seed){for(const item of items)item.optionOrder=S.settings.shuffleOptions&&item.renderType!=='fill'?stableOptionOrder(item.q,seed):[...item.q.options];return items}
function toast(msg){let e=document.createElement('div');e.className='toast';e.textContent=msg;document.body.append(e);setTimeout(()=>e.remove(),1800)}
function saveSeen(id){S.seen[id]=Date.now();queueSave()}
function normalizeAnswerSymbols(v=''){return String(v).normalize('NFKC').replace(/[•∙・]/g,'·').replace(/([nN])\s*[.·]\s*m/gi,'N·m').replace(/[−–—]/g,'-').replace(/(\d)\s*[~～]\s*(\d)/g,'$1-$2').replace(/(\d)\s*(?:至|到)\s*(\d)/g,'$1-$2').replace(/(\d)\s*[xX×*]\s*(\d)/g,'$1×$2')}
function cleanAns(a){return normalizeAnswerSymbols(a).replace(/^[A-F][\.．、]\s*/i,'').replace(/\s+/g,'').replace(/[“”"'‘’。.!！?？,，、;；:：()（）\[\]【】]/g,'').toLowerCase()}
function arrayEq(a,b){return a.length===b.length&&a.every(x=>b.includes(x))}
function fillTokens(s){return String(s||'').split(/[、,，;；\n\/]+/).map(cleanAns).filter(Boolean)}
function stripFillFraming(v){return v.replace(/^(正确答案是|正确答案为|答案是|答案为|应填写|应填入|应为|填写|填入)/,'')}
function containsEveryAnswerExactly(raw,answers){let rest=stripFillFraming(cleanAns(raw));for(const expected of [...answers].map(cleanAns).sort((a,b)=>b.length-a.length)){let at=rest.indexOf(expected);if(at<0)return false;rest=rest.slice(0,at)+rest.slice(at+expected.length)}return rest.length===0}
function answerCorrect(item,answer){try{const q=item?.q;if(!validatePaperItem(q,item?.renderType,item?.renderType==='fill'?item?.fillLevel:'standard'))return false;if(item.renderType==='fill'){if(typeof answer!=='string')return false;let entry=fillEntry(q,item.fillLevel),raw=answer,accepted=entry?.accepted||[];if(accepted.some(x=>cleanAns(x)===cleanAns(raw)))return true;let exp=questionAnswers(q,'fill',item.fillLevel);return containsEveryAnswerExactly(raw,exp)}if(item.renderType==='multiple'){if(!Array.isArray(answer)||answer.some(x=>typeof x!=='string'))return false;let got=[...new Set(answer.map(cleanAns))].sort(),exp=q.answers.map(cleanAns).sort();return arrayEq(got,exp)}if(typeof answer!=='string')return false;return cleanAns(answer)===cleanAns(q.answers[0]||'')}catch(e){return false}}
function formatDuration(ms=0){let sec=Math.max(0,Math.round(ms/1000)),h=Math.floor(sec/3600),m=Math.floor((sec%3600)/60),s=sec%60;return h?`${h}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`:`${m}:${String(s).padStart(2,'0')}`}
function formatQTime(ms=0){let sec=Math.max(0,Math.round(ms/1000));return sec<60?`${sec}秒`:`${Math.floor(sec/60)}分${String(sec%60).padStart(2,'0')}秒`}
function isActiveExam(){return !!(session&&session.kind==='exam'&&!session.finished)}
function isTimedSession(){return !!(session&&session.kind!=='fillStudy'&&!session.finished)}
function initExamTimer(){if(!isTimedSession())return;session.totalActiveMs=0;session.items.forEach(x=>x.timeMs=0);session._activeIndex=current;session._activeSince=document.hidden?null:performance.now();startTimerTicker()}
function flushExamTimer(){if(!isTimedSession()||session._activeSince==null)return;let now=performance.now(),d=Math.max(0,now-session._activeSince);session.totalActiveMs=(session.totalActiveMs||0)+d;let item=session.items[session._activeIndex];if(item&&!item.checked)item.timeMs=(item.timeMs||0)+d;session._activeSince=now}
function pauseExamTimer(){if(!isTimedSession())return;flushExamTimer();session._activeSince=null;if(isActiveExam())saveSession(false);else saveStore();updateTimerUI()}
function resumeExamTimer(){if(!isTimedSession()||document.hidden)return;session._activeIndex=current;session._activeSince=performance.now();updateTimerUI()}
function liveTotalMs(){if(!isTimedSession())return session?.totalActiveMs||0;let v=session.totalActiveMs||0;if(session._activeSince!=null)v+=Math.max(0,performance.now()-session._activeSince);return v}
function liveQuestionMs(){if(!session)return 0;let item=session.items[current],v=item?.timeMs||0;if(isTimedSession()&&session._activeSince!=null&&session._activeIndex===current&&!item?.checked)v+=Math.max(0,performance.now()-session._activeSince);return v}
function updateTimerUI(){let a=$('#examTimer'),b=$('#questionTimer'),c=$('#examTimerSide');if(a)a.textContent=formatDuration(liveTotalMs());if(b)b.textContent=formatQTime(liveQuestionMs());if(c)c.textContent=formatDuration(liveTotalMs())}
function startTimerTicker(){stopTimerTicker();timerTicker=setInterval(updateTimerUI,500);updateTimerUI()}
function stopTimerTicker(){if(timerTicker){clearInterval(timerTicker);timerTicker=null}}
function switchQuestion(i){if(!session||i<0||i>=session.items.length)return;if(isTimedSession())flushExamTimer();current=i;if(isTimedSession()){session._activeIndex=current;session._activeSince=document.hidden?null:performance.now();if(isActiveExam())saveSession(false);else queueSave()}renderQuestion('question')}
async function copyText(text){try{if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(text);return true}}catch(e){}try{let t=document.createElement('textarea');t.value=text;t.style.position='fixed';t.style.opacity='0';document.body.appendChild(t);t.select();let ok=document.execCommand('copy');t.remove();return ok}catch(e){return false}}
async function shareSite(){if(location.protocol==='file:'){alert('当前是手机本地文件版，无法生成别人可直接访问的网页链接。正式部署成网址后，这个按钮会直接调出系统分享面板，可选择微信、QQ等应用。');return}let url=location.href.split('#')[0],data={title:'神人刘题库训练站',text:'神人刘题库训练站：刷题、模拟考试、错题和计时分析',url};try{if(navigator.share){await navigator.share(data);return}}catch(e){if(e&&e.name==='AbortError')return}if(await copyText(url))toast('题库链接已复制，可粘贴到微信或QQ');else prompt('复制下面的题库链接：',url)}
async function installApp(){if(window.matchMedia?.('(display-mode: standalone)').matches){toast('题库已经以桌面应用方式打开');return}if(location.protocol==='file:'){alert('“一键安装到桌面”需要网站先部署为 HTTPS 网址。本地文件版仍可使用，但浏览器不会提供标准PWA安装。正式上线后点这里即可安装；不支持自动安装的浏览器会提示“添加到主屏幕”。');return}if(deferredInstallPrompt){deferredInstallPrompt.prompt();let r=await deferredInstallPrompt.userChoice;deferredInstallPrompt=null;toast(r.outcome==='accepted'?'已确认安装':'已取消安装');return}alert('如果浏览器没有自动弹出安装窗口，请打开浏览器菜单，选择“添加到主屏幕 / 安装应用”。安装后桌面会出现“神人刘题库”图标。')}
function armBackGuard(){try{history.pushState({srGuard:true},'',location.href)}catch(e){}}
function initBackGuard(){if(backGuardReady)return;backGuardReady=true;try{history.replaceState({srRoot:true},'',location.href);armBackGuard();window.addEventListener('popstate',()=>{let sm=$('#sourceModal'),setm=$('#settingsModal');if(sm&&!sm.classList.contains('hidden')){closeSource();armBackGuard();return}if(setm&&!setm.classList.contains('hidden')){setm.classList.add('hidden');armBackGuard();return}if(session||view!=='home'){navHome();setTimeout(armBackGuard,0);return}if(!backExitArmed){backExitArmed=true;toast('再返回一次可退出题库');clearTimeout(backRearmTimer);backRearmTimer=setTimeout(()=>{backExitArmed=false;armBackGuard()},1800);return}clearTimeout(backRearmTimer);backExitArmed=false})}catch(e){}}
function protectUnload(e){if(isTimedSession())flushExamTimer();saveStore();if(isActiveExam()){saveSession();e.preventDefault();e.returnValue='';return ''}}


const knowledge=[
 {keys:['扭力扳手','力矩'],title:'扭矩工具',text:'扭力扳手的核心是按规定力矩进行紧固或复检。使用时通常要求受力平稳、工具与紧固件正确对中，并按校验/检定要求管理；达到设定值后应停止继续加力，避免过紧。'},
 {keys:['风扳机'],title:'风动工具',text:'风扳机用于快速预紧或紧固，必须按工艺规定选型并配套正确套筒。它不能替代扭力扳手的定量复检功能，持续冲击时间也应受控制。'},
 {keys:['随车单'],title:'随车单',text:'随车单与具体订单/车辆随行，用于承载装配、异常或后续处理等关联信息。记忆时把它理解成“跟着这台车走的记录载体”。'},
 {keys:['不合格品','不合格'],title:'不合格品控制',text:'不合格品管理的关键不是“先想办法继续生产”，而是先防止误用和混用。题库中的典型流程为隔离、标识、记录、审理、处置。'},
 {keys:['首件'],title:'首件管理',text:'首件检验的价值在于尽早发现换人、换料、换工装、设备调整等变化带来的系统性偏差，避免缺陷批量扩散。'},
 {keys:['质量检查点'],title:'质量检查点',text:'质量检查点强调把检验要求放到现场并可视化。题库相关内容包括检查点标识、检验文件、量检具、检验记录以及留存样件等。'},
 {keys:['4M1E','4M','变化点'],title:'4M1E变化点',text:'4M1E通常对应人（Man）、机（Machine）、料（Material）、法（Method）、环（Environment）。人员、设备、材料、方法或环境发生变化时，都可能带来质量波动，因此要进行变化点管理。'},
 {keys:['5S','整理','整顿'],title:'5S',text:'“整理”解决要与不要，“整顿”解决需要的物品放哪里、怎么快速找到。整顿强调定置、标识、取用方便和减少寻找时间，不要把“整理”和“整顿”的目的混在一起。'},
 {keys:['PDCA'],title:'PDCA循环',text:'PDCA按计划（Plan）—执行（Do）—检查（Check）—处置/改进（Act）循环推进。它不是一次性流程，而是持续改善、循环上升。'},
 {keys:['QC活动','QC小组'],title:'QC活动',text:'QC活动围绕问题选题、现状把握、目标设定、原因分析、对策与效果确认等步骤展开。题库第70题特别考查前四步的先后顺序。'},
 {keys:['标准作业','生产节拍','循环时间','作业顺序','标准手持'],title:'标准作业',text:'标准作业以人的动作为中心，常把生产节拍、作业顺序、标准手持作为关键要素。生产节拍回答“目标多久产一件”，循环时间回答“操作者完成一轮实际需要多久”，标准手持是维持节拍所需的最少在制品。'},
 {keys:['少人化','省人化'],title:'少人化与省人化',text:'少人化强调随生产量变化灵活配置最少人员；省人化更偏向通过改善或自动化减少人工作业。两者名称相近，是题库里的高频易混点。'},
 {keys:['自働化','自动化','均衡化'],title:'精益三概念',text:'自动化是设备代替人工作业；自働化强调把人的判断能力赋予设备，异常时能报警或停止；均衡化（平准化）则是把产品数量和种类尽量平均化生产。'},
 {keys:['MES'],title:'MES',text:'MES即制造执行系统，处在计划层与现场执行之间，关注从订单下达到产品完成过程中的执行、跟踪和现场资源状态。'},
 {keys:['BOM'],title:'BOM',text:'BOM是物料清单，用来描述一个最终产品由哪些零部件和原材料构成，以及数量等结构关系。'},
 {keys:['ERP'],title:'ERP',text:'ERP即企业资源计划，强调把财务、采购、生产、销售、库存等业务资源整合到统一管理平台。'},
 {keys:['TPM'],title:'TPM',text:'TPM强调全员参与的生产维护，目标是提高设备综合效率、减少故障和损失。题库还把设备点检、自主保养等内容与TPM联系起来。'},
 {keys:['点检','五定'],title:'设备点检',text:'点检是按规定项目和标准确认设备状态，常见“五定”包括定点、定法、定标、定期、定人。发现异常后应先消除异常并按要求确认设备状态，而不是凭经验带病运行。'},
 {keys:['KYT','危险预知'],title:'KYT',text:'KYT是危险预知训练，核心是作业前识别潜在危险、预测可能事故并形成预防措施，强调员工共同参与和现场纠正。'},
 {keys:['安全色','蓝色','红色'],title:'安全色',text:'安全色用于快速传递安全信息。题库中明确考到蓝色表示指令、必须遵守的约定；红色常用于禁止、停止或危险性更强的警示场景。'},
 {keys:['劳保','耳塞','安全帽','口罩'],title:'劳动防护',text:'劳保用品应根据岗位风险和作业内容配置，而不是凭个人感觉。噪声、粉尘、吊装等不同风险对应不同防护用品，进入生产区域前应按规定穿戴。'},
 {keys:['行车','吊装','吊具'],title:'吊装安全',text:'吊装作业强调额定能力、吊具状态和人员安全。不得超负荷、不明物不吊、吊物不得越过人员头顶；吊具出现裂纹、变形、凹槽等异常应按要求处理。'},
 {keys:['线束','管路'],title:'线束/管路装配',text:'线束和管路要做到走向合理、固定可靠、无干涉、无磨碰，并避开热源和尖锐部位。插接件要到位、可靠，装配后还要检查是否存在弓折、悬垂或交叉等问题。'},
 {keys:['防错'],title:'防错',text:'防错的目标是从设计和过程上避免错误发生，或在异常出现时立即识别并阻止继续流出。防错装置本身也需要点检，因为装置也可能失效。'},
 {keys:['纠正措施','预防措施','纠正是'],title:'纠正相关概念',text:'“纠正”侧重消除已经发现的不合格本身；“纠正措施”侧重消除导致不合格的原因，避免再次发生；“预防措施”针对潜在不合格或潜在不期望情况的原因。'},
 {keys:['看板'],title:'看板/目视化',text:'看板和可视化的核心是让生产状态、问题和需求一目了然，使现场人员能快速判断并采取行动。看板的发行数量和规则应随实际生产条件按制度调整。'},
 {keys:['七大浪费','浪费'],title:'七大浪费',text:'精益生产把不产生顾客价值的活动视为浪费。常见浪费包括等待、搬运、库存、不良/返修、过量生产、过度加工和多余动作等。'},
 {keys:['多技能','多能工'],title:'多技能工',text:'多技能工通过有计划的多岗位训练，使人员能在班组或产线内承担多个岗位，增强人员配置弹性，也是少人化的重要基础。'},
 {keys:['层级会议','一层级会议'],title:'层级会议',text:'层级会议用于逐级暴露和解决现场问题。一层级会议更贴近班组现场，通常围绕安全、质量关注点、生产任务等当班重点展开。'},
 {keys:['工装'],title:'工装管理',text:'工装要经过验证、点检/周检和必要的易损件管理。未经验证或验证不合格的工装不应投入生产；定位销、导套、定位块等易损件需按要求维护或更换。'},
 {keys:['ABS'],title:'ABS',text:'ABS的中文名称是防抱死制动系统。它通过防止制动时车轮完全抱死，帮助车辆保持一定的转向和稳定能力。'},
 {keys:['五大工具','APQP','PPAP','FMEA','SPC','MSA'],title:'质量五大工具',text:'汽车行业常说的质量五大工具为APQP、PPAP、FMEA、SPC、MSA。题库第130题直接考查这组缩写。'}
];
function matchedKnowledge(q){let t=q.stem+' '+q.options.join(' '),out=[];for(const k of knowledge){if(k.keys.some(x=>t.toLowerCase().includes(x.toLowerCase())))out.push(k);if(out.length>=2)break}return out}
function topicName(q){return (q.tags||[]).slice(0,2).join('、')||'现场管理'}
function genericSelectionReason(q,answers,know){let stem=displayText(q.stem),joined=answers.join('、');if(SELECTION_REASONS[q.id])return SELECTION_REASONS[q.id];if(/(日期|频次|责任单位|负责|标识线|代号|范围|期限|mm|\dT)/i.test(stem))return `“${joined}”是本题所依据的现场制度、工艺或编码中的明确要求。此类题的关键是把对象与规定值准确对应，实际执行仍以现场最新版文件为准。`;if(/(是指|称为|简称|定义|全称|中文名称)/.test(stem))return `题干给出的特征与“${joined}”的定义相符；其他相近概念只覆盖其中一部分，或适用对象不同。`;if(/(首先|第一时间|步骤|顺序|作业|操作|处理|使用)/.test(stem))return `“${joined}”能够满足题干所要求的操作顺序或控制目的，可先控制风险、质量状态或过程异常，避免问题继续扩大。`;if(know.length)return `选择“${joined}”的依据是：${know[0].text}`;return `题干考查${topicName(q)}中的具体要求。“${joined}”同时满足题干给出的对象、条件和目的，其他选项至少有一项关键限定不符合。`}
function trueJudgeReason(q,know){let tags=q.tags||[];if(JUDGE_REASONS[q.id])return JUDGE_REASONS[q.id];if(know.length)return `本题判“对”。判断依据是：${know[0].text}`;if(tags.includes('安全与劳保'))return '本题判“对”。题干要求针对作业危险源采取控制措施，能够降低人员受伤、误操作或事故扩大的风险。';if(tags.includes('质量管理'))return '本题判“对”。题干做法能够明确产品状态、保留过程证据或阻止不合格品继续流转，符合现场质量控制逻辑。';if(tags.includes('设备管理'))return '本题判“对”。按规定点检、停机、保养或确认设备状态，可以预防故障扩大并保证设备处于可用状态。';if(tags.includes('工具与装配'))return '本题判“对”。题干做法能够保护工具精度、保证装配一致性，并减少误用、磕碰或失效风险。';if(tags.includes('精益生产'))return '本题判“对”。题干做法围绕稳定流程、暴露问题和减少浪费展开，符合精益现场管理的基本逻辑。';if(tags.includes('生产与物流'))return '本题判“对”。题干要求能够保持生产与物料流转受控，使数量、状态和流向可识别、可追溯。';return '本题判“对”。题干中的对象、条件和动作能够完整对应，没有把适用范围扩大、缩小或省略关键步骤。'}
function optionReason(q,o,isCorrect,summary){let manual=OPTION_NOTES[q.id]?.[o];if(manual)return manual;let text=displayText(o);if(isCorrect)return `符合题干的关键条件。${fillEntry(q)?.why||summary}`;if(/以上都对|以上都是|全部正确/.test(text))return '只有在其余列项全部成立时才能选择该项；本题并不满足“全部成立”的条件。';if(/以上都不|都不正确|全部错误/.test(text))return '题目中存在符合要求的具体选项，因此不能作出“全部不正确”的判断。';if(/不用管|无所谓|随意|直接装|继续作业|继续生产|无需|不需要|大声咒骂|弄丢/.test(text))return '该做法绕过了标准作业、异常反馈或风险控制，可能让安全、质量或设备问题继续扩大。';if(/主任|班组长|质量|技术|部门|车间|个人|小组/.test(text)&&/(负责|反馈|报告|单位|人员|由|向)/.test(q.stem))return '责任主体与题目所述管理层级不匹配，不能替代规定的报告或处置责任人。';if(/[0-9]|每周|每天|每月|半年|黄色|红色|蓝色|白色/.test(text)&&/(日期|频次|间隔|代号|颜色|期限|mm|T)/i.test(q.stem))return '该数值、频次或标识与本题采用的工艺和管理标准不符。';if(/不属于|不包括|不正确|错误|不合适|不宜/.test(q.stem))return '该项正是题干要求识别的例外或错误做法，不能把它与其余合规项目混为一类。';return `该项与题干所限定的对象、条件或目的不完全一致，不能替代正确项“${questionAnswers(q).join('、')}”。`}
function explain(q,renderType=q.type,fillLevel='standard'){let know=matchedKnowledge(q),answers=questionAnswers(q,renderType,fillLevel),entry=renderType==='fill'?fillEntry(q,fillLevel):null,summary='',correction='';if(q.type==='judge'&&renderType!=='fill'){if(q.answers[0]==='错'){correction=JUDGE_CORRECTIONS[q.id]||'题干存在不符合规定的表述，应去掉绝对化或省略关键条件的部分，并按现场标准改写。';summary=JUDGE_REASONS[q.id]||'本题判“错”。题干至少有一处做法、定义或适用条件与正确要求不一致；具体错误点和改正方法见下方。'}else summary=trueJudgeReason(q,know)}else summary=entry?.why||genericSelectionReason(q,answers,know);let opts=q.type==='judge'||renderType==='fill'?[]:q.options.map(o=>{let ok=q.answers.some(a=>cleanAns(a)===cleanAns(o));return {ok,text:displayText(o),reason:optionReason(q,o,ok,summary)}});let memory=renderType==='fill'?'遮住答案，按空格顺序完整写出关键词，再回看原题确认语境。':q.type==='multiple'?'把正确项按作业先后或检查对象整理成关键词组，复习时脱离选项完整说出。':q.type==='judge'?(q.answers[0]==='错'?'记住改正后的完整说法和错误原因，不要只背一个“错”字。':'把题干中的对象、条件和动作作为一条完整规则记忆。'):'把题干和答案连成一条完整规则，再到填空模式中主动回忆。';return {summary,correction,opts,know,memory,answers,renderType}}

function updateWatermark(){let e=$('#watermark');if(!e)return;let m=S.settings.watermark;e.textContent=m==='cn'?'神人刘':m==='en'?'SHENREN LIU':m==='off'?'':'神人刘 · SHENREN LIU';document.documentElement.dataset.theme=S.settings.theme||'light'}
function technicalQuestions(){return Q.filter(q=>q.technicalVerified)}
function reviewQuestions(){let ids=new Set(Object.keys(S.reviewFlags||{}).filter(id=>S.reviewFlags[id]).map(Number));return Q.filter(q=>ids.has(q.id))}
function stats(){let seen=Object.keys(S.seen).length,fav=S.favorites.length,wrong=Object.values(S.wrong).filter(x=>x&&x.count>0).length,mastered=Object.values(S.mastery).filter(x=>x==='mastered').length,review=reviewQuestions().length;return {seen,fav,wrong,mastered,review}}
function app(html,scrollMode='top'){let y=window.scrollY;$('#main').innerHTML=html;updateWatermark();requestAnimationFrame(()=>{if(scrollMode==='preserve')window.scrollTo({top:y,behavior:'instant'});else if(scrollMode==='question'){let q=$('.section-title')||$('.question-card');if(q)q.scrollIntoView({block:'start',behavior:'instant'});else window.scrollTo({top:0,behavior:'instant'})}else window.scrollTo({top:0,behavior:'instant'})})}
function navHome(force=false){if(!force&&isActiveExam()&&!confirm('确定放弃当前考试吗？本卷进度将被清除。'))return;if(isTimedSession())pauseExamTimer();if(isActiveExam()){S.lastSession=null;saveStore()}stopTimerTicker();document.body.classList.remove('sheet-open');view='home';session=null;current=0;renderHome()}

function renderHome(){view='home';const st=stats();let single=Q.filter(q=>q.type==='single').length,multi=Q.filter(q=>q.type==='multiple').length,judge=Q.filter(q=>q.type==='judge').length,fill=Q.filter(isFillEligible).length,enhancedFill=Q.filter(q=>isFillEligible(q,'enhanced')).length,technical=technicalQuestions().length;app(`
<section class="hero"><div class="panel hero-main"><div class="pill">HOS 应知应会 · 本地离线题库</div><h1>神人刘题库训练站</h1><p>顺序背题、两级填空训练、填空增强版真实模拟、错题自动收集、收藏与逐题解析。增强填空已纳入适合改编的判断题，并采用独立题干。</p><div class="hero-tags"><span class="pill">总题数 ${Q.length}</span><span class="pill">单选 ${single}</span><span class="pill">多选 ${multi}</span><span class="pill">判断 ${judge}</span><span class="pill">标准填空 ${fill}</span><span class="pill">增强填空 ${enhancedFill}</span><span class="pill">符号英文已核 ${technical}</span></div></div>
<div class="panel stats-card"><div class="stat"><b>${st.seen}</b><span>已练题目</span></div><div class="stat"><b>${st.wrong}</b><span>当前错题</span></div><div class="stat"><b>${st.fav}</b><span>收藏题目</span></div><div class="stat"><b>${st.mastered}</b><span>已标掌握</span></div><div class="stat"><b>${st.review}</b><span>待复核题目</span></div></div></section>
${S.lastSession?`<div class="panel resume-banner"><div><b>检测到未完成的考试：${esc(S.lastSession.title)}</b><span>已答 ${S.lastSession.answers.filter(a=>a!=null&&a!==''&&(!Array.isArray(a)||a.length)).length}/${S.lastSession.ids.length} · 停在第 ${S.lastSession.current+1} 题 · 有效用时 ${formatDuration(S.lastSession.totalActiveMs)}</span></div><div><button class="btn primary" onclick="resumeLastSession()">继续上次考试</button><button class="btn" onclick="discardLastSession()">放弃</button></div></div>`:''}
${BANK_AUDIT_ERRORS.length?`<div class="notice danger-notice"><b>题库数据自检未通过：</b>${esc(BANK_AUDIT_ERRORS.slice(0,5).join('；'))}</div>`:`<div class="notice"><b>题库数据自检通过</b> · 题号、题型、选项、答案映射与已复核答案数量均正常。</div>`}
<div class="section-title"><div><h2>开始训练</h2><p>默认模拟卷约 15% 为人工复核改写的填空题</p></div></div>
<section class="mode-grid">
${modeCard('📖','顺序背题','按原题号从前往后背，可即时看答案和解析',`startStudy('sequence')`)}
${modeCard('📅','今日复习','优先安排错题、不熟、高耗时、到期和长期未见题',`startTodayReview()`)}
${modeCard('⚖️','全库均衡复习','按曝光、间隔、错题、辅助答对、耗时、掌握度和SRS均衡覆盖全库',`startBalancedReview()`)}
${modeCard('🔀','随机刷题','打乱题目顺序，适合查漏补缺',`startStudy('random')`)}
${modeCard('Aa','符号英文专项',`集中练习 ${technical} 道含型号、单位、公式或英文缩写且已复核的题`,`startTechnicalStudy()`)}
${modeCard('!','待复核清单','把自己怀疑有错字、符号或答案的题集中留存',`renderReviewList()`)}
${modeCard('📝','模拟考试','30/50/100/150题，默认少量混入填空题',`renderExamSetup('mixed')`)}
${modeCard('🎯','填空强化模拟','固定55题：15单选 + 10多选 + 10判断 + 20填空',`renderRealExamSetup('fillStrong')`)}
${modeCard('🏁','真实考试模拟','固定45题：15单选 + 10多选 + 10判断 + 10填空',`renderRealExamSetup('real')`)}
${modeCard('🧠','纯填空背诵','可选标准版或增强版；增强版含重新改写的判断题',`renderFillStudySetup()`)}
${modeCard('⌨️','纯填空模拟','可选标准版或增强版，不显示选项并优先抽取近期未考题',`renderExamSetup('fill')`)}
${modeCard('❌','错题本','按刚做错、反复错、辅助后会做、高耗时、已纠正待巩固分类',`renderWrongBook()`)}
${modeCard('⭐','收藏夹','收藏题目时连同解析一起保留',`openCollection('fav')`)}
${modeCard('🔎','题库搜索','按题号、关键词、答案或知识点搜索',`renderSearch()`)}
${modeCard('📊','学习记录','查看近期成绩和薄弱题型',`renderHistory()`)}
${modeCard('🗺️','507题掌握度地图','查看真正掌握、错题、到期、高耗时、收藏与待复核状态',`renderMasteryMap()`)}
</section>
<div class="section-title"><div><h2>学习进度</h2><p>数据仅保存在当前浏览器</p></div></div>
<section class="dashboard-grid"><div class="panel pad"><b>总体覆盖</b><div class="progressbar" style="margin:12px 0 7px"><i style="width:${Math.round(st.seen/Q.length*100)}%"></i></div><span class="muted">已练 ${st.seen}/${Q.length} 题 · ${Math.round(st.seen/Q.length*100)}%</span></div>
<div class="panel pad"><b>备份学习数据</b><p class="muted" style="font-size:13px">换手机或清浏览器前，建议先导出一次。</p><div style="display:flex;gap:8px;flex-wrap:wrap"><button class="btn small" onclick="exportData()">导出数据</button><button class="btn small" onclick="$('#importFile').click()">导入数据</button><input id="importFile" type="file" accept="application/json" hidden onchange="importData(this.files[0])"></div></div></section>`)}
function modeCard(icon,title,desc,onclick){return `<div class="panel mode-card"><div class="mode-icon">${icon}</div><h3>${title}</h3><p>${desc}</p><button class="btn primary small" onclick="${onclick}">进入</button></div>`}

function todayReviewQuestions(limit=50){let now=Date.now();return Q.map(q=>{let l=S.learning[q.id]||{},wrong=S.wrong[q.id]?.count||0,mastery=S.mastery[q.id]||'',seen=S.seen[q.id]||0,avg=l.attempts?l.totalMs/l.attempts:0,score=wrong*100+(mastery==='fuzzy'?70:mastery==='new'?40:0)+(l.due&&l.due<=now?35:0)+(avg>=30000?25:0)+(seen?Math.min(20,(now-seen)/86400000):30);return {q,score}}).sort((a,b)=>b.score-a.score||a.q.id-b.q.id).slice(0,limit).map(x=>x.q)}
function startTodayReview(){startStudySession(todayReviewQuestions(),'今日复习')}

function buildItems(list,mode='study',fillRatio=0,fillLevel='standard'){let arr=list.map(q=>({q,renderType:q.type,fillLevel:'standard',answer:null,checked:false,correct:null,showExplanation:false,assisted:false,revealed:false,attemptRecorded:false,confidence:'',timeMs:0,optionOrder:[...q.options]}));if(mode==='fill'){arr=arr.filter(x=>isFillEligible(x.q,fillLevel)).map(x=>({...x,renderType:'fill',fillLevel}))}else if(mode==='mixed'&&fillRatio>0){let eligible=shuffle(arr.filter(x=>isFillEligible(x.q)));let n=Math.min(eligible.length,Math.round(arr.length*fillRatio/100));let ids=new Set(eligible.slice(0,n).map(x=>x.q.id));arr=arr.map(x=>ids.has(x.q.id)?{...x,renderType:'fill'}:x)}return arr}
function startStudySession(list,title){view='question';let paperId=makePaperId(),items=applyOptionOrders(buildItems(list,'study'),paperId);session={kind:'study',items,started:Date.now(),title,paperId,finished:false};current=0;initExamTimer();renderQuestion()}
function startStudy(order='sequence',list=null){let qs=list||Q;if(order==='random')qs=shuffle(qs);startStudySession(qs,order==='random'?'随机刷题':'顺序背题')}
function renderFillStudySetup(){view='examSetup';let a=Q.filter(isFillEligible).length,b=Q.filter(q=>isFillEligible(q,'enhanced')).length;app(`<div class="panel exam-setup"><div class="section-title" style="margin-top:0"><div><h2>纯填空背诵</h2><p>选择背诵难度后进入，答案与解析直接展开</p></div><button class="btn" onclick="navHome()">返回</button></div><div class="setup-grid"><button class="panel mode-card" onclick="startFillStudy('sequence','standard')"><h3>标准填空</h3><p>${a}题 · 精选核心知识点，适合第一轮记忆</p></button><button class="panel mode-card" onclick="startFillStudy('sequence','enhanced')"><h3>增强填空</h3><p>${b}题 · 覆盖更多单选、多选和适合改编的判断题</p></button></div></div>`)}
function startFillStudy(order='sequence',level='standard'){view='question';let qs=Q.filter(q=>isFillEligible(q,level));if(order==='random')qs=shuffle(qs);let items=buildItems(qs,'fill',0,level);session={kind:'fillStudy',mode:'fillStudy',fillLevel:level,items,started:Date.now(),title:level==='enhanced'?'增强填空背诵':'标准填空背诵'};current=0;renderQuestion()}
function startTechnicalStudy(){startStudySession(shuffle(technicalQuestions()),'符号英文专项')}
function startBalancedReview(){let picked=coveragePick(Q,Math.min(100,Q.length),new Set(),true);startStudySession(picked,'全库均衡复习')}
function openCollection(kind){let ids=kind==='fav'?S.favorites:Object.keys(S.wrong).filter(id=>{let w=S.wrong[id];return w&&(w.count>0||w.corrected)}).map(Number);let list=Q.filter(q=>ids.includes(q.id));if(!list.length){app(`<div class="panel empty"><h2>${kind==='fav'?'收藏夹':'错题本'}还是空的</h2><p>做题时点收藏，或答错题后这里会自动出现。</p><button class="btn primary" onclick="navHome()">返回首页</button></div>`);return}startStudySession(list,kind==='fav'?'收藏夹':'错题重练')}
function wrongCategory(id){let w=S.wrong[id]||{},l=S.learning[id]||{},avg=l.timedAttempts?l.totalMs/l.timedAttempts:0;if(w.corrected)return 'corrected';if((w.wrongStreak||0)>=2||(w.wrongTotal||0)>=3)return 'repeated';if(w.recentResult==='assistedCorrect'||w.assistedCorrect)return 'assisted';if(avg>=30000)return 'slow';return 'recent'}
function wrongCategoryName(k){return {recent:'刚做错',repeated:'反复错',assisted:'辅助后会做',slow:'高耗时',corrected:'已纠正待巩固'}[k]||'全部'}
function wrongIds(category='all'){return Object.keys(S.wrong).map(Number).filter(id=>{let w=S.wrong[id];return w&&(w.count>0||w.corrected)&&(category==='all'||wrongCategory(id)===category)})}
function renderWrongBook(){view='wrongBook';let cats=['recent','repeated','assisted','slow','corrected'],all=wrongIds();app(`<div class="section-title"><div><h2>错题本</h2><p>连续2次独立答对后转为已纠正待巩固</p></div><button class="btn" onclick="navHome()">返回</button></div><div class="setup-grid">${cats.map(k=>`<button class="panel mode-card" onclick="startWrongCategory('${k}')"><h3>${wrongCategoryName(k)}</h3><p>${wrongIds(k).length}题</p></button>`).join('')}</div><div style="margin-top:16px"><button class="btn primary" onclick="startWrongCategory('all')" ${all.length?'':'disabled'}>练全部 ${all.length} 题</button></div>`)}
function startWrongCategory(category){let ids=wrongIds(category),list=Q.filter(q=>ids.includes(q.id));if(!list.length)return toast('该分类暂无题目');startStudySession(list,`错题重练 · ${wrongCategoryName(category)}`)}

function getSourcePages(q){return (q?.sourceImages||[q?.sourceImage||1]).map(Number)}
function renderReviewList(){view='review';let list=reviewQuestions();app(`<div class="section-title"><div><h2>待复核清单</h2><p>本清单只保存在当前浏览器，可导出后反馈题号和原题页</p></div><button class="btn" onclick="navHome()">返回</button></div>${list.length?`<div class="toolbar"><button class="btn primary" onclick="startReviewStudy()">开始逐题复核</button><button class="btn" onclick="exportReviewReport()">导出复核记录</button></div><div class="review-list">${list.map(q=>`<div class="panel review-item"><h4>#${q.id} · 原题第${getSourcePages(q).join('、')}页</h4><p>${esc(displayText(q.stem))}</p><div style="margin-top:8px"><button class="btn small" onclick="reviewOne(${q.id})">打开题目</button> <button class="btn small" onclick="openQuestionSource(${q.id})">查看原图</button> <button class="btn small danger" onclick="clearReviewFlag(${q.id})">移出清单</button></div></div>`).join('')}</div>`:`<div class="panel empty"><h2>目前没有待复核题目</h2><p>做题时点“标记待复核”，怀疑的题就会出现在这里。</p><button class="btn primary" onclick="navHome()">返回首页</button></div>`}`)}
function startReviewStudy(){let list=reviewQuestions();if(!list.length)return toast('待复核清单还是空的');startStudySession(list,'待复核题目')}
function toggleReviewFlag(id){S.reviewFlags=S.reviewFlags||{};let flagged=!!S.reviewFlags[id];if(flagged)delete S.reviewFlags[id];else S.reviewFlags[id]=Date.now();saveStore();if(view==='question')renderQuestion('preserve');else if(view==='review')renderReviewList();toast(flagged?'已移出待复核清单':'已加入待复核清单')}
function clearReviewFlag(id){if(S.reviewFlags)delete S.reviewFlags[id];saveStore();renderReviewList()}
function reviewReportText(list=reviewQuestions()){let lines=['神人刘题库待复核记录','导出时间：'+new Date().toLocaleString(),''];for(const q of list)lines.push(`#${q.id}｜原题第${getSourcePages(q).join('、')}页｜${displayText(q.stem)}`);return lines.join('\n')}
function exportReviewReport(){let list=reviewQuestions();if(!list.length)return toast('待复核清单还是空的');let blob=new Blob([reviewReportText(list)],{type:'text/plain;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`神人刘题库待复核记录_${new Date().toISOString().slice(0,10)}.txt`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}

function examSetupPool(mode){let type=$('#typeFilter')?.value||'all',level=$('#fillLevel')?.value||'standard';let pool=Q.filter(q=>type==='all'||q.type===type);return mode==='fill'?pool.filter(q=>isFillEligible(q,level)):pool}
function refreshExamCounts(mode,notify=false){let max=examSetupPool(mode).length,buttons=$$('#countBtns button'),active=buttons.find(b=>b.classList.contains('active'));for(const b of buttons)b.disabled=Number(b.dataset.n)>max;if(!active||active.disabled){let next=[...buttons].filter(b=>!b.disabled).sort((a,b)=>Number(b.dataset.n)-Number(a.dataset.n))[0];buttons.forEach(b=>b.classList.remove('active'));if(next)next.classList.add('active');if(notify)toast(`当前题池最多 ${max} 题，已自动调整题量`)}let info=$('#poolMax');if(info)info.textContent=`当前最多 ${max} 题`}
function renderExamSetup(mode){view='examSetup';let max=mode==='fill'?Q.filter(isFillEligible).length:Q.length,ratio=S.settings.defaultFillRatio||15;app(`<div class="panel exam-setup"><div class="section-title" style="margin-top:0"><div><h2>${mode==='fill'?'纯填空模拟':'模拟考试'}</h2><p>${mode==='fill'?'选择标准或增强难度，连续考试优先不重复':'覆盖优先组卷，提交后统一判分'}</p></div><button class="btn" onclick="navHome()">返回</button></div>
<div class="setup-grid"><div class="field"><label>题目数量 <span id="poolMax" class="muted"></span></label><div class="count-buttons" id="countBtns">${[30,50,100,150].map(n=>`<button class="btn ${n===50?'active':''}" data-n="${n}">${n}题</button>`).join('')}</div></div>
<div class="field"><label>抽题范围</label><select id="typeFilter" onchange="refreshExamCounts('${mode}',true)"><option value="all">全部题型</option>${mode==='fill'?'':`<option value="single">仅单选</option><option value="multiple">仅多选</option><option value="judge">仅判断</option>`}</select></div>
${mode==='fill'?`<div class="field"><label>填空难度</label><select id="fillLevel" onchange="refreshExamCounts('${mode}',true)"><option value="standard">标准填空（${Q.filter(isFillEligible).length}题）</option><option value="enhanced">增强填空（${Q.filter(q=>isFillEligible(q,'enhanced')).length}题，含判断改编）</option></select></div>`:''}
${mode==='mixed'?`<div class="field"><label>填空题比例 <span id="ratioText">${ratio}%</span></label><div class="range-row"><input id="fillRatio" type="range" min="0" max="30" step="5" value="${ratio}" oninput="$('#ratioText').textContent=this.value+'%'"><span class="muted">建议 10–20%</span></div></div>`:''}
<div class="field"><label>考试规则</label><select id="examRule"><option value="normal">普通模式（未答可交卷）</option><option value="strict">严格模式（必须全部作答）</option></select></div></div>
<div class="notice" style="margin-top:16px">${mode==='fill'?`题量会随标准/增强难度动态调整，绝不会静默少出题。题干均按主动回忆方式组织。`:`默认会从标准填空池中抽取约 <b>${ratio}%</b> 改成填空；题量会随题型筛选动态调整。`}</div>
<div style="margin-top:18px"><button class="btn primary" onclick="beginExam('${mode}')">开始考试</button></div></div>`);$$('#countBtns button').forEach(b=>b.onclick=()=>{if(b.disabled)return;$$('#countBtns button').forEach(x=>x.classList.remove('active'));b.classList.add('active')});refreshExamCounts(mode)}
function makePaperId(){return `P${Date.now().toString(36)}${Math.random().toString(36).slice(2,8)}`}
function beginExam(mode){let n=Number($('#countBtns .active')?.dataset.n||0),level=mode==='fill'?($('#fillLevel')?.value||'standard'):'standard',pool=examSetupPool(mode);if(!n||n>pool.length){toast(`当前题池最多 ${pool.length} 题，不能生成所选题量`);refreshExamCounts(mode);return}let picked=coveragePick(pool,n),ratio=mode==='mixed'?Number($('#fillRatio').value):100;S.settings.defaultFillRatio=mode==='mixed'?ratio:S.settings.defaultFillRatio;let items=buildItems(picked,mode,ratio,level);if(items.length!==n){toast('组卷题量异常，已阻止进入考试');return}let paperId=makePaperId();session={kind:'exam',mode,fillLevel:level,strict:$('#examRule').value==='strict',items,started:Date.now(),title:mode==='fill'?(level==='enhanced'?'增强填空模拟':'标准填空模拟'):'模拟考试',finished:false,rotationRecorded:false,paperId};current=0;initExamTimer();saveSession();renderQuestion()}

function renderRealExamSetup(mode='fillStrong'){view='examSetup';let fillCount=mode==='real'?10:20,total=35+fillCount,title=mode==='real'?'真实考试模拟':'填空强化模拟',eligible=Q.filter(q=>isFillEligible(q,'enhanced')).length;app(`<div class="panel exam-setup"><div class="section-title" style="margin-top:0"><div><h2>${title}</h2><p>固定题型结构，按连续间隔惩罚与累计曝光均衡轮换</p></div><button class="btn" onclick="navHome()">返回</button></div>
<div class="dashboard-grid" style="margin-top:8px"><div class="panel pad"><b>单选题</b><div style="font-size:30px;font-weight:800">15</div></div><div class="panel pad"><b>多选题</b><div style="font-size:30px;font-weight:800">10</div></div><div class="panel pad"><b>判断题</b><div style="font-size:30px;font-weight:800">10</div></div><div class="panel pad"><b>增强填空</b><div style="font-size:30px;font-weight:800">${fillCount}</div></div></div>
<div class="setup-grid" style="margin-top:18px"><div class="field"><label>试卷总题数</label><div class="notice"><b>${total} 题</b> · 题型数量固定</div></div><div class="field"><label>考试规则</label><select id="realExamRule"><option value="normal">普通模式（未答可交卷）</option><option value="strict">严格模式（必须全部作答）</option></select></div></div>
<div class="notice" style="margin-top:16px">填空从 <b>${eligible}</b> 道增强填空题中抽取；同一重复题组不会进入同一张试卷，最近 1～10 场按连续权重降级。</div>
<div style="margin-top:18px"><button class="btn primary" onclick="beginRealExam('${mode}')">开始${title}</button></div></div>`)}
function beginRealExam(mode='fillStrong'){view='question';let fillCount=mode==='real'?10:20,used=new Set(),singles=pickRealRegular('single',15,used);singles.forEach(q=>used.add(q.id));let multiples=pickRealRegular('multiple',10,used);multiples.forEach(q=>used.add(q.id));let judges=pickRealRegular('judge',10,used);judges.forEach(q=>used.add(q.id));let fillQs=coveragePick(Q.filter(q=>isFillEligible(q,'enhanced')),fillCount,used);fillQs.forEach(q=>used.add(q.id));if(fillQs.length<fillCount||singles.length<15||multiples.length<10||judges.length<10){toast('当前题库不足以按固定比例组卷');return}let items=buildItems([...singles,...multiples,...judges],'study');items.push(...buildItems(fillQs,'fill',0,'enhanced'));let paperId=makePaperId(),title=mode==='real'?'真实考试模拟':'填空强化模拟（原填空增强版真实模拟）';session={kind:'exam',mode,fillLevel:'enhanced',strict:$('#realExamRule').value==='strict',items,started:Date.now(),title,finished:false,rotationRecorded:false,paperId};current=0;initExamTimer();saveSession();renderQuestion()}

function recordStudyExposure(item){if(session?.kind==='exam'||item.exposureRecorded)return;let l=S.learning[item.q.id]||(S.learning[item.q.id]=baseLearning());l.totalExposure++;if(item.renderType==='fill')l.fillExposure++;else l.regularExposure++;item.exposureRecorded=true}
function renderQuestion(scrollMode='question'){view='question';if(!session||!session.items.length)return navHome(true);let item=session.items[current],q=item.q;recordStudyExposure(item);saveSeen(q.id);let isExam=session.kind==='exam',isFillStudy=session.kind==='fillStudy';if(isFillStudy)item.checked=true;let locked=!isExam&&item.checked&&!isFillStudy;let reveal=isFillStudy||(!isExam&&(item.checked||item.showExplanation));let ex=explain(q,item.renderType,item.fillLevel);let fav=S.favorites.includes(q.id),flagged=!!S.reviewFlags?.[q.id];let mastery=S.mastery[q.id]||'';app(`<div class="section-title"><div><h2>${esc(session.title)}</h2><p>第 ${current+1}/${session.items.length} 题 · 原题号 #${q.id}</p></div><button class="btn" onclick="navHome()">返回题库</button></div>
<div class="study-layout"><div class="panel question-card"><div class="q-head"><div class="q-meta"><span class="tag ${item.renderType}">${typeName(item.renderType)}</span>${q.tags.map(t=>`<span class="tag">${esc(displayText(t))}</span>`).join('')}${q.technicalVerified?'<span class="tag verified">符号英文已核</span>':''}${q.ocrWarning?'<span class="tag warn">建议核对原图</span>':''}</div><div class="q-head-tools"><button class="btn small ${flagged?'flagged':''}" onclick="toggleReviewFlag(${q.id})">${flagged?'已标待复核':'标记待复核'}</button><button class="btn small ${fav?'good':''}" onclick="toggleFav(${q.id})">${fav?'★ 已收藏':'☆ 收藏'}</button></div></div>
${isTimedSession()?`<div class="exam-timebar"><span>⏱ 总用时 <b id="examTimer">${formatDuration(liveTotalMs())}</b></span><span>本题 <b id="questionTimer">${formatQTime(liveQuestionMs())}</b></span><small>切到后台或锁屏自动暂停</small></div>`:''}
<div class="q-stem">${esc(fillStem(q,item.renderType,item.fillLevel))}</div>${isFillStudy?renderFillStudyAnswer(item):renderInput(item,locked)}
${isFillStudy?`<div class="q-actions"><div class="left"><button class="btn" onclick="openQuestionSource(${q.id})">查看原题页</button></div><div class="right"><select class="btn" onchange="setMastery(${q.id},this.value)"><option value="">掌握状态</option><option value="mastered" ${mastery==='mastered'?'selected':''}>已掌握</option><option value="fuzzy" ${mastery==='fuzzy'?'selected':''}>不熟</option><option value="new" ${mastery==='new'?'selected':''}>未掌握</option></select></div></div>`:!isExam?`<div class="q-actions"><div class="left"><button class="btn primary" onclick="checkStudy()" ${item.checked?'disabled':''}>${item.checked?'已判定':'提交答案'}</button><button class="btn" onclick="showExplanation()">${reveal?'解析已展开':'查看解析'}</button><button class="btn" onclick="showAnswer()">直接看答案</button><button class="btn" onclick="openQuestionSource(${q.id})">查看原题页</button></div><div class="right"><select class="btn" onchange="setMastery(${q.id},this.value)"><option value="">掌握状态</option><option value="mastered" ${mastery==='mastered'?'selected':''}>已掌握</option><option value="fuzzy" ${mastery==='fuzzy'?'selected':''}>不熟</option><option value="new" ${mastery==='new'?'selected':''}>未掌握</option></select></div></div>${item.checked?renderConfidence(item):''}`:`<div class="q-actions"><div class="left"><span class="exam-lock-note">考试中隐藏答案、解析和原题截图</span></div><div class="right"><button class="btn" onclick="prevQ()" ${current===0?'disabled':''}>上一题</button><button class="btn primary" onclick="nextQ()">${current===session.items.length-1?'检查/交卷':'下一题'}</button></div></div>`}
${reveal?renderExplanation(q,ex,item.checked?item.correct:null,isFillStudy):''}
${!isExam?`<div class="q-actions"><div class="left"><button class="btn" onclick="prevQ()" ${current===0?'disabled':''}>上一题</button></div><div class="right"><button class="btn primary" onclick="nextQ()">${current===session.items.length-1?'完成本轮':'下一题'}</button></div></div>`:''}</div>
<aside id="answerPanel" class="panel side answer-panel"><div class="answer-panel-head"><h3>${isFillStudy?'背诵导航':'答题卡'}</h3><button class="btn small answer-panel-close" onclick="toggleAnswerPanel(false)" aria-label="关闭题号索引">关闭</button></div><div class="answer-sheet">${session.items.map((x,i)=>`<button class="sheet-item ${i===current?'current':''} ${isFillStudy&&x.checked?'done':x.answer!=null&&(!(Array.isArray(x.answer))||x.answer.length)?'done':''} ${x.correct===true?'correct':''} ${x.correct===false?'wrong':''}" onclick="jumpQ(${i})">${i+1}</button>`).join('')}</div><div style="margin-top:14px" class="muted">${isExam?`已答 ${answeredCount()}/${session.items.length}`:isFillStudy?`已看 ${session.items.filter(x=>x.checked).length}/${session.items.length}`:`已练 ${session.items.filter(x=>x.checked).length}/${session.items.length}`}</div>${isExam?`<div class="side-timing"><span>总用时</span><b id="examTimerSide">${formatDuration(liveTotalMs())}</b></div><button class="btn danger" style="width:100%;margin-top:10px" onclick="submitExam()">交卷</button>`:''}</aside></div>
<div class="sheet-backdrop" onclick="toggleAnswerPanel(false)"></div><nav class="quick-nav" aria-label="快捷翻题"><button class="btn" onclick="prevQ()" ${current===0?'disabled':''}>← 上一题</button><button class="btn index-btn" onclick="toggleAnswerPanel(true)">题号 ${current+1}/${session.items.length}</button><button class="btn primary" onclick="nextQ()">${current===session.items.length-1?(isExam?'检查/交卷':'完成本轮'):'下一题 →'}</button></nav>`,scrollMode);requestAnimationFrame(()=>{updateTimerUI();let side=$('#examTimerSide');if(side)side.textContent=formatDuration(liveTotalMs())})}
function fillStem(q,type,level='standard'){if(type!=='fill')return displayText(q.stem);return displayText(fillEntry(q,level)?.stem||q.stem)}
function renderFillStudyAnswer(item){return `<div class="fill-study-answer"><span>正确答案</span><b>${esc(questionAnswers(item.q,'fill',item.fillLevel).join('；'))}</b><small>先根据独立题干在脑中作答，再核对答案和下方的判断依据。</small></div>`}
function renderInput(item,locked){let q=item.q;if(item.renderType==='fill'){let v=Array.isArray(item.answer)?item.answer.join('、'):(item.answer||'');return `<div class="field fill-box"><textarea ${locked?'disabled':''} placeholder="请输入答案；多答案可用顿号、逗号分隔" oninput="setAnswer(this.value)">${esc(displayText(v))}</textarea><div class="fill-hint">本题题干已经人工复核，可脱离原选择题选项独立作答。</div></div>`}let multiple=q.type==='multiple',options=item.optionOrder||q.options;return `<div class="options">${options.map((o,i)=>{let sel=multiple?Array.isArray(item.answer)&&item.answer.includes(o):item.answer===o;let cls=sel?'selected':'';if(locked){let isC=q.answers.some(a=>cleanAns(a)===cleanAns(o));if(isC)cls+=' correct';else if(sel)cls+=' wrong'}return `<button class="option ${cls}" onclick="chooseOption(${i})" ${locked?'disabled':''}><span class="letter">${String.fromCharCode(65+i)}</span><span>${esc(displayText(o))}</span></button>`}).join('')}</div>`}
function setAnswer(v){session.items[current].answer=v;if(isActiveExam())queueSaveSession();else queueSave()}
function queueSaveSession(){if(saveDebounceTimer)clearTimeout(saveDebounceTimer);saveDebounceTimer=setTimeout(()=>saveSession(),350)}
function chooseOption(i){let item=session.items[current],o=(item.optionOrder||item.q.options)[i];if(item.q.type==='multiple'){let a=Array.isArray(item.answer)?[...item.answer]:[];a=a.includes(o)?a.filter(x=>x!==o):[...a,o];item.answer=a}else item.answer=o;if(isActiveExam())saveSession();else queueSave();renderQuestion('preserve')}
function baseLearning(){return {attempts:0,correct:0,wrong:0,streak:0,totalMs:0,timedAttempts:0,assistedCorrect:0,lowConfidenceCorrect:0,totalExposure:0,regularExposure:0,fillExposure:0,lastSeenRound:0,last:0,due:0}}
function updateWrongRecord(item,correct,assisted){let id=item.q.id,w=S.wrong[id]||{count:0,wrongTotal:0,wrongStreak:0,lastWrong:0,lastCorrect:0,independentCorrectStreak:0,assistedCorrect:0,recentResult:'',corrected:false},now=Date.now();if(!correct){w.count=Math.max(1,w.count||0);w.wrongTotal++;w.wrongStreak++;w.lastWrong=now;w.independentCorrectStreak=0;w.recentResult='wrong';w.corrected=false}else if(assisted){w.assistedCorrect++;w.lastCorrect=now;w.independentCorrectStreak=0;w.recentResult='assistedCorrect'}else{w.lastCorrect=now;w.wrongStreak=0;w.independentCorrectStreak++;w.recentResult='independentCorrect';if(w.count>0&&w.independentCorrectStreak>=2){w.count=0;w.corrected=true}}if(w.wrongTotal||w.count||w.corrected)S.wrong[id]=w}
function recordAggregateAttempt(item,correct){let a=S.aggregateStats||(S.aggregateStats=emptyAggregate()),type=typeName(item.renderType),ms=num(item.timeMs,0),q=item.q;a.totalAnswers++;a.totalCorrect+=correct?1:0;if(ms>0)a.totalStudyMs+=ms;let t=a.byType[type]||(a.byType[type]={attempts:0,correct:0,totalMs:0});t.attempts++;t.correct+=correct?1:0;t.totalMs+=ms;let p=a.byQuestion[q.id]||(a.byQuestion[q.id]={attempts:0,correct:0,wrong:0,totalMs:0});p.attempts++;p.correct+=correct?1:0;p.wrong+=correct?0:1;p.totalMs+=ms;for(const tag of q.tags||[]){let z=a.byTag[tag]||(a.byTag[tag]={attempts:0,correct:0,totalMs:0});z.attempts++;z.correct+=correct?1:0;z.totalMs+=ms}let week=new Date().toISOString().slice(0,10),ws=a.weeks[week]||(a.weeks[week]={attempts:0,correct:0,totalMs:0});ws.attempts++;ws.correct+=correct?1:0;ws.totalMs+=ms}
function updateLearning(item,correct,assisted=false){if(item.attemptRecorded)return false;let id=item.q.id,x=S.learning[id]||baseLearning(),now=Date.now(),ms=num(item.timeMs,0);x.attempts++;x.correct+=correct?1:0;x.wrong+=correct?0:1;x.streak=correct&&!assisted?x.streak+1:0;if(ms>0){x.totalMs+=ms;x.timedAttempts++}if(correct&&assisted)x.assistedCorrect++;x.last=now;let days=!correct?1:assisted?1:Math.min(30,Math.max(1,2**Math.min(5,x.streak-1)));x.due=now+days*86400000;S.learning[id]=x;item.attemptRecorded=true;item.assistedResult=!!(correct&&assisted);updateWrongRecord(item,correct,assisted);recordAggregateAttempt(item,correct);return true}
function checkStudy(){let item=session.items[current];if(item.checked||item.attemptRecorded)return toast('本题本轮已记录');if(item.answer==null||item.answer===''||(Array.isArray(item.answer)&&!item.answer.length)){toast('先选一个答案');return}flushExamTimer();session._activeSince=null;item.correct=answerCorrect(item,item.answer);item.checked=true;updateLearning(item,item.correct,!!item.assisted);saveStore();item.showExplanation=true;renderQuestion('preserve')}
function showExplanation(){let item=session.items[current];item.showExplanation=true;if(!item.checked)item.assisted=true;if(isActiveExam())saveSession();else queueSave();renderQuestion('preserve')}
function showAnswer(){let item=session.items[current];if(!item.checked){item.assisted=true;item.revealed=true}if(item.renderType==='fill')item.answer=questionAnswers(item.q,'fill',item.fillLevel).join('、');else item.answer=item.q.type==='multiple'?[...item.q.answers]:item.q.answers[0];item.showExplanation=true;if(isActiveExam())saveSession();else queueSave();renderQuestion('preserve')}
function renderConfidence(item){return `<div class="confidence-box"><span>本题信心：</span>${[['sure','确定会'],['hesitant','有点犹豫'],['guess','蒙的']].map(([v,t])=>`<button class="btn small ${item.confidence===v?'good':''}" onclick="setConfidence('${v}')">${t}</button>`).join('')}${item.assistedResult?'<small>本题为辅助后答对，不计独立答对</small>':''}</div>`}
function setConfidence(v){let item=session.items[current];if(!item?.checked||!['sure','hesitant','guess'].includes(v))return;let old=item.confidence;item.confidence=v;let l=S.learning[item.q.id]||baseLearning();if(item.correct&&old!=='hesitant'&&old!=='guess'&&(v==='hesitant'||v==='guess')){l.lowConfidenceCorrect++;l.due=Math.min(l.due||Infinity,Date.now()+86400000)}S.learning[item.q.id]=l;saveStore();renderQuestion('preserve')}
function renderExplanation(q,ex,correct,hideAnswer=false){let isJudge=q.type==='judge'&&ex.renderType!=='fill',reasonTitle=ex.renderType==='fill'?'为什么这样填':isJudge?(q.answers[0]==='错'?'为什么判错':'为什么判对'):'为什么这样选';return `<div class="explanation">${hideAnswer?'':`<div class="answer-box"><b>${correct===true?'✓ 回答正确':correct===false?'✗ 回答错误':'题目解析'}</b><div>正确答案：${esc(ex.answers.join('；'))}</div></div>`}<h3>${reasonTitle}</h3><div class="analysis-block">${esc(ex.summary)}</div>${ex.correction?`<h3>错在哪里，应该怎样改</h3><div class="analysis-block correction-block">${esc(ex.correction)}</div>`:''}${!isJudge&&ex.renderType!=='fill'?`<h3>每个选项为什么选或不选</h3><div class="analysis-block"><ul class="option-analysis">${ex.opts.map(x=>`<li class="${x.ok?'should-select':'should-skip'}"><b>${x.ok?'应选':'不选'} · ${esc(x.text)}</b><span>${esc(x.reason)}</span></li>`).join('')}</ul></div>`:''}${ex.know.map(k=>`<h3>${esc(k.title)} · 知识补充</h3><div class="analysis-block">${esc(k.text)}</div>`).join('')}<h3>记忆建议</h3><div class="analysis-block">${esc(ex.memory)}</div><div class="source-note">解析用于说明判断依据；公司内部制度、数值和具体作业要求以原题及现场最新版标准为准。${q.sourceNote?' '+esc(q.sourceNote):''}</div></div>`}
function prevQ(){if(current>0)switchQuestion(current-1)}
function nextQ(){let item=session?.items?.[current];if(session?.kind!=='exam'&&S.settings.confidenceRequired&&item?.checked&&!item.confidence)return toast('请先选择本题信心度');if(current<session.items.length-1){switchQuestion(current+1);return}if(session.kind==='exam'){submitExam()}else{toast('本轮已完成');navHome(true)}}
function toggleAnswerPanel(open){let panel=$('#answerPanel'),backdrop=$('.sheet-backdrop');if(!panel)return;if(window.matchMedia('(max-width:900px)').matches){panel.classList.toggle('open',open);backdrop?.classList.toggle('open',open);document.body.classList.toggle('sheet-open',open);if(open)requestAnimationFrame(()=>panel.querySelector('.sheet-item.current')?.scrollIntoView({block:'center'}))}else if(open){panel.scrollIntoView({block:'start',behavior:'smooth'});panel.classList.add('index-flash');setTimeout(()=>panel.classList.remove('index-flash'),700)}}
function jumpQ(i){toggleAnswerPanel(false);switchQuestion(i)}
function answeredCount(){return session.items.filter(x=>x.answer!=null&&x.answer!==''&&(!Array.isArray(x.answer)||x.answer.length)).length}
function saveSession(flush=true){if(!isActiveExam())return;if(flush)flushExamTimer();S.lastSession={bankVersion:BANK_VERSION,schemaVersion:STORE_SCHEMA_VERSION,kind:'exam',mode:session.mode,title:session.title,strict:!!session.strict,fillLevel:session.fillLevel||'standard',current,ids:session.items.map(x=>x.q.id),answers:session.items.map(x=>x.answer),renderTypes:session.items.map(x=>x.renderType),fillLevels:session.items.map(x=>x.fillLevel||'standard'),optionOrders:session.items.map(x=>x.optionOrder||x.q.options),timeMs:session.items.map(x=>Math.round(x.timeMs||0)),totalActiveMs:Math.round(session.totalActiveMs||0),started:session.started||Date.now(),rotationRecorded:!!session.rotationRecorded,paperId:session.paperId||makePaperId()};saveStore()}
function resumeLastSession(){let snap=sanitizeLastSession(S.lastSession);if(!snap){S.lastSession=null;saveStore();renderHome();return toast('上次考试数据已损坏或版本不兼容，已安全清除')}let byId=new Map(Q.map(q=>[q.id,q]));session={kind:'exam',mode:snap.mode,title:snap.title,strict:snap.strict,fillLevel:snap.fillLevel,started:snap.started,finished:false,rotationRecorded:snap.rotationRecorded,paperId:snap.paperId,items:snap.ids.map((id,i)=>({q:byId.get(id),renderType:snap.renderTypes[i],fillLevel:snap.fillLevels[i],answer:snap.answers[i],optionOrder:snap.optionOrders[i],checked:false,correct:null,showExplanation:false,assisted:false,revealed:false,attemptRecorded:false,confidence:'',timeMs:snap.timeMs[i]||0})),totalActiveMs:snap.totalActiveMs};current=snap.current;session._activeIndex=current;session._activeSince=document.hidden?null:performance.now();startTimerTicker();renderQuestion();toast('已恢复上次考试，关闭期间未计时')}
function discardLastSession(){if(!S.lastSession||!confirm('确定放弃上次未完成考试吗？该进度无法恢复。'))return;S.lastSession=null;saveStore();renderHome();toast('已放弃上次考试')}
function toggleFav(id){let i=S.favorites.indexOf(id);if(i>=0)S.favorites.splice(i,1);else S.favorites.push(id);saveStore();renderQuestion('preserve');toast(i>=0?'已取消收藏':'已收藏')}
function setMastery(id,v){if(v)S.mastery[id]=v;else delete S.mastery[id];saveStore();toast('掌握状态已更新')}

function submitExam(){if(!isActiveExam())return;let unansweredItems=session.items.map((x,i)=>({x,i})).filter(z=>z.x.answer==null||z.x.answer===''||(Array.isArray(z.x.answer)&&!z.x.answer.length)),unanswered=unansweredItems.length;if(unanswered&&session.strict){current=unansweredItems[0].i;session._activeIndex=current;saveSession();renderQuestion();toast(`还有 ${unanswered} 题未作答，已跳到第一道未答题`);return}if(unanswered&&!confirm(`还有 ${unanswered} 题未作答，确定交卷吗？`))return;flushExamTimer();session._activeSince=null;session.finished=true;stopTimerTicker();document.body.classList.remove('sheet-open');if(!session.rotationRecorded){recordExamRotation(session.items);session.rotationRecorded=true}let c=0;for(const item of session.items){item.correct=answerCorrect(item,item.answer);item.checked=true;updateLearning(item,item.correct,false);if(item.correct)c++}let score=Math.round(c/session.items.length*100),total=session.totalActiveMs||session.items.reduce((a,x)=>a+(x.timeMs||0),0),timed=session.items.filter(x=>(x.timeMs||0)>0),avg=timed.length?timed.reduce((a,x)=>a+x.timeMs,0)/timed.length:0,high=session.items.filter(x=>(x.timeMs||0)>=30000&&(!avg||(x.timeMs||0)>avg*1.5)),typeTimes={};for(const x of session.items){let t=typeName(x.renderType),z=typeTimes[t]||(typeTimes[t]={total:0,count:0});if((x.timeMs||0)>0){z.total+=x.timeMs;z.count++}}let rec={time:Date.now(),mode:session.title,count:session.items.length,correct:c,score,durationMs:Math.round(total),avgMs:Math.round(avg),highCount:high.length,highIds:high.map(x=>x.q.id),typeTimes:Object.fromEntries(Object.entries(typeTimes).map(([k,v])=>[k,v.count?Math.round(v.total/v.count):0])),questionTimes:session.items.map(x=>({id:x.q.id,type:typeName(x.renderType),ms:Math.round(x.timeMs||0),correct:!!x.correct,assisted:!!x.assistedResult,confidence:x.confidence||''})),paperId:session.paperId||makePaperId(),ids:session.items.map(x=>x.q.id),renderTypes:session.items.map(x=>x.renderType),fillLevels:session.items.map(x=>x.fillLevel||'standard'),optionOrders:session.items.map(x=>x.optionOrder||x.q.options)};let ag=S.aggregateStats||(S.aggregateStats=emptyAggregate());ag.totalExams++;ag.highestScore=Math.max(ag.highestScore||0,score);ag.recentScores=[...(ag.recentScores||[]),score].slice(-20);S.history.unshift(rec);S.history=S.history.slice(0,50);S.lastSession=null;saveStore();renderResult(c,score)}
function renderResult(c,score){view='result';let wrong=session.items.filter(x=>!x.correct),total=session.totalActiveMs||session.items.reduce((a,x)=>a+(x.timeMs||0),0),avg=total/Math.max(1,session.items.length);let byType={},timeByType={};for(const x of session.items){let t=typeName(x.renderType);byType[t]=byType[t]||[0,0];byType[t][1]++;if(x.correct)byType[t][0]++;let z=timeByType[t]||(timeByType[t]={total:0,count:0});z.total+=x.timeMs||0;z.count++}let slow=[...session.items].sort((a,b)=>(b.timeMs||0)-(a.timeMs||0)),high=slow.filter(x=>(x.timeMs||0)>=30000&&(x.timeMs||0)>avg*1.5);session.highTimeItems=high;let timingRows=Object.entries(timeByType).map(([t,v])=>`<div class="stat"><b>${formatQTime(v.total/v.count)}</b><span>${t}平均</span></div>`).join('');app(`<div class="panel result-hero"><div class="score-ring" style="--pct:${score}%"><b>${score}分</b></div><div><h2 style="margin:0">${score>=90?'非常稳':score>=75?'整体不错':score>=60?'及格了，继续补弱项':'建议先刷错题再模拟'}</h2><p class="muted">答对 ${c}/${session.items.length} · 错题 ${wrong.length} 道已自动加入错题本</p><div class="result-grid">${Object.entries(byType).map(([t,v])=>`<div class="stat"><b>${v[0]}/${v[1]}</b><span>${t}</span></div>`).join('')}</div></div></div>
<div class="section-title"><div><h2>⏱ 用时分析</h2><p>高耗时题：单题至少30秒，且超过本场平均用时的1.5倍</p></div></div><section class="dashboard-grid timing-summary"><div class="panel pad"><b>整场有效用时</b><div class="big-time">${formatDuration(total)}</div></div><div class="panel pad"><b>平均每题</b><div class="big-time">${formatQTime(avg)}</div></div><div class="panel pad"><b>高耗时题</b><div class="big-time">${high.length}道</div></div></section><div class="panel pad" style="margin-top:14px"><h3 style="margin-top:0">各题型平均用时</h3><div class="result-grid">${timingRows}</div></div>
<div class="section-title"><div><h2>高耗时 / 最慢题</h2><p>${high.length?`已自动标出 ${high.length} 道需要提高熟练度的题`:'本场没有达到“高耗时”阈值的题，下面仍列出最慢的题供参考'}</p></div><button class="btn primary" onclick="retrySlowCurrent()" ${high.length?'':'disabled'}>重练高耗时题</button></div><div class="review-list">${slow.slice(0,10).map((x,i)=>`<div class="panel review-item timing-item ${high.includes(x)?'slow-alert':''}"><h4>${i+1}. #${x.q.id} ${esc(displayText(x.q.stem))}</h4><p><b>${formatQTime(x.timeMs||0)}</b> · ${typeName(x.renderType)} · ${x.correct?'答对':'答错'} ${high.includes(x)?'· <span class="slow-badge">高耗时</span>':''}</p><button class="btn small" style="margin-top:8px" onclick="reviewOne(${x.q.id})">重做这题</button></div>`).join('')}</div>
<details class="panel pad timing-details"><summary>查看全部 ${session.items.length} 道题的逐题用时</summary><div class="timing-all-list">${session.items.map((x,i)=>`<button class="timing-row ${x.correct?'ok':'bad'}" onclick="reviewOne(${x.q.id})"><span>${i+1}. #${x.q.id} · ${typeName(x.renderType)}</span><b>${formatQTime(x.timeMs||0)}</b><em>${x.correct?'✓':'✗'}</em></button>`).join('')}</div></details>
<div class="section-title"><div><h2>本场复盘</h2><p>自动合并答错、未答、高耗时、辅助后答对与低信心正确题</p></div><div><button class="btn" onclick="navHome()">回首页</button> <button class="btn" onclick="redoCurrentPaper()">重做本卷</button> <button class="btn primary" onclick="reviewCurrentSession()">一键本场复盘</button></div></div><div class="review-list">${wrong.length?wrong.map(x=>`<div class="panel review-item"><h4>#${x.q.id} ${esc(fillStem(x.q,x.renderType,x.fillLevel))}</h4><p>本题用时：${formatQTime(x.timeMs||0)} · 正确答案：${esc(questionAnswers(x.q,x.renderType,x.fillLevel).join('；'))}</p><button class="btn small" style="margin-top:8px" onclick="reviewOne(${x.q.id})">重做这题</button></div>`).join(''):`<div class="panel empty">本场没有答错题；仍可复盘高耗时或低信心题。</div>`}</div>`)}
function retryWrongCurrent(){let list=session.items.filter(x=>!x.correct).map(x=>x.q);if(!list.length)return toast('本次没有错题');startStudy('sequence',list)}
function retrySlowCurrent(){let list=(session?.highTimeItems||[]).map(x=>x.q);if(!list.length)return toast('本次没有达到阈值的高耗时题');startStudy('sequence',list)}
function reviewCurrentSession(){let high=new Set((session?.highTimeItems||[]).map(x=>x.q.id)),ids=new Set((session?.items||[]).filter(x=>!x.correct||high.has(x.q.id)||x.assistedResult||['hesitant','guess'].includes(x.confidence)).map(x=>x.q.id)),list=Q.filter(q=>ids.has(q.id));if(!list.length)return toast('本场没有需要复盘的题');startStudySession(list,'本场复盘')}
function reviewOne(id){startStudy('sequence',Q.filter(q=>q.id===id))}
function startPaperFromRecord(rec){let bad=rec?.paperDamaged||!rec?.ids?.length||!Array.isArray(rec.renderTypes)||!Array.isArray(rec.fillLevels)||rec.renderTypes.length!==rec.ids.length||rec.fillLevels.length!==rec.ids.length||new Set(rec.ids.map(Number)).size!==rec.ids.length;if(!bad)for(let i=0;i<rec.ids.length;i++){let q=Q.find(x=>x.id===Number(rec.ids[i])),t=rec.renderTypes[i],l=t==='fill'?rec.fillLevels[i]:'standard';if(!VALID_IDS.has(Number(rec.ids[i]))||!validatePaperItem(q,t,l)){bad=true;break}}if(bad)return toast('该历史试卷数据损坏，无法重做');let byId=new Map(Q.map(q=>[q.id,q])),paperId=`${rec.paperId||makePaperId()}-R`,items=rec.ids.map((id,i)=>{let q=byId.get(Number(id)),raw=rec.optionOrders?.[i];return {q,renderType:rec.renderTypes[i],fillLevel:rec.renderTypes[i]==='fill'?rec.fillLevels[i]:'standard',answer:null,optionOrder:Array.isArray(raw)&&raw.length===q.options.length?[...raw]:stableOptionOrder(q,rec.paperId||paperId),checked:false,correct:null,showExplanation:false,assisted:false,revealed:false,attemptRecorded:false,confidence:'',timeMs:0}});session={kind:'exam',mode:'redo',title:`重做：${rec.mode||'历史试卷'}`,strict:false,fillLevel:'enhanced',started:Date.now(),finished:false,rotationRecorded:true,paperId,items};current=0;initExamTimer();saveSession();renderQuestion()}
function redoCurrentPaper(){let rec={mode:session.title,paperId:session.paperId,ids:session.items.map(x=>x.q.id),renderTypes:session.items.map(x=>x.renderType),fillLevels:session.items.map(x=>x.fillLevel||'standard')};startPaperFromRecord(rec)}
function redoHistoryPaper(i){startPaperFromRecord(S.history?.[i])}

function renderSearch(){view='search';app(`<div class="section-title"><div><h2>题库搜索</h2><p>支持题号、题干、选项、答案、知识标签</p></div><button class="btn" onclick="navHome()">返回</button></div><div class="panel pad"><div class="toolbar"><input id="searchInput" style="flex:1;min-width:220px" placeholder="例如：扭力扳手 / MES / 170 / 不合格品" oninput="doSearch(this.value)"><select id="searchType" onchange="doSearch($('#searchInput').value)"><option value="all">全部题型</option><option value="single">单选</option><option value="multiple">多选</option><option value="judge">判断</option></select></div><div id="searchResults" class="search-results"><div class="empty">输入关键词开始搜索</div></div></div>`);setTimeout(()=>$('#searchInput')?.focus(),50)}
function doSearch(v){let kw=v.trim().toLowerCase(),type=$('#searchType').value;if(!kw){$('#searchResults').innerHTML='<div class="empty">输入关键词开始搜索</div>';return}let list=Q.filter(q=>(type==='all'||q.type===type)&&([q.id,q.stem,...q.options,...q.answers,...q.tags].join(' ').toLowerCase().includes(kw))).slice(0,100);$('#searchResults').innerHTML=list.length?list.map(q=>`<div class="panel search-item"><strong>#${q.id} · ${typeName(q.type)} · ${esc(displayText(q.stem))}</strong><p>答案：${esc(q.answers.map(displayText).join('；'))} · ${esc(q.tags.join(' / '))}</p><div style="margin-top:8px"><button class="btn small" onclick="reviewOne(${q.id})">打开题目</button> <button class="btn small" onclick="openQuestionSource(${q.id})">原题页</button></div></div>`).join(''):'<div class="empty">没有匹配结果</div>'}

function allTagStats(){let map=S.aggregateStats?.byTag||{};return Object.entries(map).map(([tag,z])=>{let n=num(z.attempts,0),correct=num(z.correct,0),ms=num(z.totalMs,0),slow=num(z.slow,0);return {tag,n,correct,ms,slow,wrong:n-correct,rate:n?correct/n:0,wrongRate:n?(n-correct)/n:0,slowRate:n?slow/n:0}}).sort((a,b)=>a.rate-b.rate||b.wrongRate-a.wrongRate||b.n-a.n)}
function weakTagStats(){return allTagStats().filter(x=>x.n>=3).slice(0,5)}
function renderHistory(){view='history';let h=S.history||[],ag=S.aggregateStats||emptyAggregate(),scores=ag.recentScores||[],avg=scores.length?Math.round(scores.reduce((a,b)=>a+b,0)/scores.length):0,allTags=allTagStats(),weak=allTags.filter(x=>x.n>=3).slice(0,5),insufficient=allTags.filter(x=>x.n<3).slice(0,8),tagButton=x=>`<button class="btn" onclick="startTagStudy('${esc(x.tag)}')"><b>${esc(x.tag)}</b><span>${x.n}题次 · 错误${x.wrong}次/${Math.round(x.wrongRate*100)}% · 正确率${Math.round(x.rate*100)}% · 平均${formatQTime(x.n?x.ms/x.n:0)}</span></button>`;app(`<div class="section-title"><div><h2>学习记录</h2><p>详细记录保留50场；累计统计永久保留</p></div><button class="btn" onclick="navHome()">返回</button></div><section class="dashboard-grid"><div class="panel pad"><b>累计模拟</b><div style="font-size:32px;font-weight:800">${ag.totalExams||0}</div></div><div class="panel pad"><b>近期平均</b><div style="font-size:32px;font-weight:800">${avg}分</div></div><div class="panel pad"><b>最高分</b><div style="font-size:32px;font-weight:800">${ag.highestScore||0}分</div></div><div class="panel pad"><b>总学习时长</b><div style="font-size:32px;font-weight:800">${formatDuration(ag.totalStudyMs||0)}</div></div></section><div class="panel pad" style="margin-top:14px"><h3 style="margin-top:0">薄弱知识点 Top 5</h3>${weak.length?`<div class="tag-weak-list">${weak.map(tagButton).join('')}</div>`:'<p class="muted">每个标签至少累计3题次后进入正式排行。</p>'}${insufficient.length?`<details style="margin-top:12px"><summary>数据不足（少于3题次）</summary><div class="tag-weak-list" style="margin-top:10px">${insufficient.map(tagButton).join('')}</div></details>`:''}</div><div class="panel pad" style="margin-top:14px"><ul class="list-clean history-list">${h.length?h.map((x,i)=>`<li><span>${new Date(x.time).toLocaleString()} · ${esc(x.mode)} · ${x.count}题${x.durationMs!=null?`<small>用时 ${formatDuration(x.durationMs)} · 平均 ${formatQTime(x.avgMs||0)} · 高耗时 ${x.highCount||0}题</small>`:''}</span><span class="history-actions"><b>${x.score}分</b>${x.ids?.length&&!x.paperDamaged?`<button class="btn small" onclick="redoHistoryPaper(${i})">重做本卷</button>`:x.ids?.length?'<small>试卷数据损坏</small>':''}</span></li>`).join(''):'<li class="muted">暂无考试记录</li>'}</ul></div>`)}
function startTagStudy(tag){let list=Q.filter(q=>q.tags?.includes(tag));if(!list.length)return toast('该标签暂无题目');startStudySession(list,`专项：${tag}`)}

function reviewHistorySlow(i){let r=(S.history||[])[i],ids=r?.highIds||[];if(!ids.length)return toast('这场考试没有高耗时题');let list=Q.filter(q=>ids.includes(q.id));startStudy('sequence',list)}

function masteryStatus(q){let l=S.learning[q.id]||{},w=S.wrong[q.id]||{},avg=l.timedAttempts?l.totalMs/l.timedAttempts:0;if(S.reviewFlags[q.id])return '待复核';if((w.wrongStreak||0)>=2)return '反复错';if((w.count||0)>0)return '错题';if(l.due&&l.due<=Date.now())return 'SRS到期';if(avg>=30000)return '高耗时';if(S.favorites.includes(q.id))return '收藏';if((w.independentCorrectStreak||0)>=2||(S.mastery[q.id]==='mastered'&&(l.attempts||0)>0))return '熟练';if(S.mastery[q.id]==='fuzzy')return '不熟';return S.seen[q.id]?'不熟':'未见'}
function renderMasteryMap(){view='masteryMap';let rows=Q.map(q=>({q,status:masteryStatus(q)})),mastered=rows.filter(x=>x.status==='熟练'),seven=Date.now()-7*86400000,new7=mastered.filter(x=>(S.wrong[x.q.id]?.lastCorrect||S.learning[x.q.id]?.last||0)>=seven).length,due=rows.filter(x=>['SRS到期','错题','反复错','不熟'].includes(x.status)).length,everWrong=Object.values(S.wrong).filter(w=>(w.wrongTotal||0)>0),corrected=everWrong.filter(w=>w.corrected).length;app(`<div class="section-title"><div><h2>507题掌握度地图</h2><p>看过不等于掌握；熟练要求有效作答证据</p></div><button class="btn" onclick="navHome()">返回</button></div><section class="dashboard-grid"><div class="panel pad"><b>真正掌握率</b><div class="big-time">${Math.round(mastered.length/Q.length*100)}%</div></div><div class="panel pad"><b>近7天新增掌握</b><div class="big-time">${new7}</div></div><div class="panel pad"><b>待复习数量</b><div class="big-time">${due}</div></div><div class="panel pad"><b>错题纠正率</b><div class="big-time">${everWrong.length?Math.round(corrected/everWrong.length*100):0}%</div></div></section><div class="panel pad" style="margin-top:14px"><div class="mastery-map">${rows.map(x=>`<button class="mastery-cell" data-status="${x.status}" title="#${x.q.id} ${x.status}" onclick="reviewOne(${x.q.id})"><b>${x.q.id}</b><small>${x.status}</small></button>`).join('')}</div></div>`)}

function openQuestionSource(id){let q=Q.find(x=>x.id===Number(id));if(!q)return toast('未找到题目原图');sourcePages=getSourcePages(q);sourcePage=sourcePages[0];let m=$('#sourceModal');m.classList.remove('hidden');renderSource()}
function openSource(page){sourcePages=[];sourcePage=Math.max(1,Math.min(111,Number(page)||1));let m=$('#sourceModal');m.classList.remove('hidden');renderSource()}
function renderSource(){let img=$('#sourceImage');img.src=`image${sourcePage}.webp`;let span=sourcePages.length>1?` · 本题跨第 ${sourcePages.join('、')} 页`:'';$('#sourceTitle').textContent=`原题截图 · 第 ${sourcePage}/111 页${span}`;img.onerror=()=>{img.alt='原题图片未找到';toast('原题图片未找到')};}
function closeSource(){$('#sourceModal').classList.add('hidden')}
function sourcePrev(){if(sourcePage>1){sourcePage--;renderSource()}}
function sourceNext(){if(sourcePage<111){sourcePage++;renderSource()}}

function openSettings(){let m=$('#settingsModal');m.classList.remove('hidden');$('#themeSetting').value=S.settings.theme;$('#wmSetting').value=S.settings.watermark;$('#ratioSetting').value=S.settings.defaultFillRatio||15;if($('#shuffleSetting'))$('#shuffleSetting').value=S.settings.shuffleOptions===false?'off':'on';if($('#confidenceSetting'))$('#confidenceSetting').value=S.settings.confidenceRequired?'required':'optional';let standard=Q.filter(isFillEligible).length,enhanced=Q.filter(q=>isFillEligible(q,'enhanced')).length,added=enhanced-standard,multi=Q.filter(q=>q.type==='multiple'&&isFillEligible(q,'enhanced')).length,single=Q.filter(q=>q.type==='single'&&isFillEligible(q,'enhanced')).length,judge=Q.filter(q=>q.type==='judge'&&isFillEligible(q,'enhanced')).length;if($('#versionStats'))$('#versionStats').innerHTML=`<b>版本与完整性</b><br>v2.2 · ${Q.length}题 · 标准填空${standard} · 增强新增${added} · 合计${enhanced}<br>增强池来源：单选${single} + 多选${multi} + 判断${judge} · Schema ${STORE_SCHEMA_VERSION}`}
function saveSettings(){S.settings.theme=$('#themeSetting').value;S.settings.watermark=$('#wmSetting').value;S.settings.defaultFillRatio=Number($('#ratioSetting').value);S.settings.shuffleOptions=$('#shuffleSetting')?.value!=='off';S.settings.confidenceRequired=$('#confidenceSetting')?.value==='required';saveStore();$('#settingsModal').classList.add('hidden');toast('设置已保存')}
function resetData(){if(!confirm('确定清空错题、收藏、掌握状态和考试记录吗？'))return;S=freshDefaultStore();saveStore();$('#settingsModal').classList.add('hidden');document.body.classList.remove('sheet-open');renderHome();toast('学习数据已清空')}
function exportData(){S.settings.lastBackup=Date.now();saveStore();let blob=new Blob([JSON.stringify(S,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`神人刘题库学习数据_${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function importData(file){if(!file)return;let r=new FileReader();r.onload=()=>{try{let d=JSON.parse(r.result);if(!d||typeof d!=='object'||Array.isArray(d))throw Error('根节点必须是对象');let sourceVersion=schemaVersionOf(d);if(d.history!=null&&!Array.isArray(d.history))throw Error('history字段格式错误');let migrated=hydrateStore(d);S=migrated;saveStore();document.body.classList.remove('sheet-open');renderHome();toast(sourceVersion===STORE_SCHEMA_VERSION?'学习数据已安全导入':`旧版学习数据已迁移到Schema ${STORE_SCHEMA_VERSION}`)}catch(e){toast(`导入失败：${e.message||'数据结构不正确'}`)}};r.readAsText(file)}

window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstallPrompt=e});
window.addEventListener('appinstalled',()=>{deferredInstallPrompt=null;toast('神人刘题库已安装到桌面')});
document.addEventListener('visibilitychange',()=>{if(document.hidden)pauseExamTimer();else resumeExamTimer()});
window.addEventListener('beforeunload',protectUnload);
Object.assign(window,{navHome,startStudy,startTodayReview,startBalancedReview,startTagStudy,renderFillStudySetup,startFillStudy,startTechnicalStudy,openCollection,renderWrongBook,startWrongCategory,renderReviewList,startReviewStudy,toggleReviewFlag,clearReviewFlag,exportReviewReport,reviewReportText,getSourcePages,renderExamSetup,refreshExamCounts,beginExam,renderRealExamSetup,beginRealExam,resumeLastSession,discardLastSession,chooseOption,setAnswer,checkStudy,showExplanation,showAnswer,setConfidence,prevQ,nextQ,jumpQ,toggleAnswerPanel,toggleFav,setMastery,submitExam,retryWrongCurrent,retrySlowCurrent,reviewCurrentSession,reviewOne,redoCurrentPaper,redoHistoryPaper,reviewHistorySlow,renderSearch,doSearch,renderHistory,renderMasteryMap,openQuestionSource,openSource,closeSource,sourcePrev,sourceNext,openSettings,saveSettings,resetData,exportData,importData,shareSite,installApp,$,__V22_TEST__:{getStore:()=>structuredClone(S),getSession:()=>session,duplicateGroups:DUPLICATE_GROUPS,coveragePick:(pool,n,blocked,balanced)=>coveragePick(pool,n,blocked,balanced),recordExamRotation,stableOptionOrder,flush:()=>{flushExamTimer();saveStore()}}});
updateWatermark();initBackGuard();renderHome();
})();
