const fs=require('fs'),vm=require('vm');
function cl(){const s=new Set();return {add:k=>s.add(k),remove:k=>s.delete(k),toggle(k,on){on?s.add(k):s.delete(k)},contains:k=>s.has(k)}}
function boot(initial=''){
  const main={innerHTML:''},watermark={textContent:''},store={shenrenliu_qbank_v1:initial};
  const controls={'#realExamRule':{value:'normal'},'#countBtns .active':{dataset:{n:'30'}},'#examRule':{value:'normal'},'#fillRatio':{value:'15'},'#typeFilter':{value:'all'},'#sprintCountBtns .active':{dataset:{n:'30'}}};
  const document={hidden:false,documentElement:{dataset:{}},body:{classList:cl(),append(){}},querySelector:s=>s==='#main'?main:s==='#watermark'?watermark:controls[s]||null,querySelectorAll:()=>[],addEventListener(){},createElement(){return {style:{},classList:cl(),append(){},remove(){},click(){},select(){}}},execCommand(){return true}};
  const localStorage={getItem:k=>store[k]||null,setItem:(k,v)=>store[k]=v};
  const c={window:{addEventListener(){},matchMedia:()=>({matches:false}),scrollTo(){},scrollY:0,isSecureContext:false},document,localStorage,location:{protocol:'file:',href:'file:///test'},navigator:{},history:{pushState(){},replaceState(){}},performance:{now:()=>1000},requestAnimationFrame:f=>f(),setTimeout:()=>0,clearTimeout(){},setInterval:()=>0,clearInterval(){},structuredClone:o=>JSON.parse(JSON.stringify(o)),confirm:()=>true,prompt(){},alert(){},Blob:function(){},URL:{createObjectURL:()=>'',revokeObjectURL(){}},FileReader:function(){}};
  Object.assign(c.window,{window:c.window,document,localStorage,location:c.location,navigator:c.navigator});vm.createContext(c);for(const f of ['questions.js','pedagogy.js','enhanced-fill.js','app.js'])vm.runInContext(fs.readFileSync(f,'utf8'),c,{filename:f});return {c,store,main};
}
function ok(v,m){if(!v)throw Error(m)}
function answerAndSubmit(x,round){const s=x.c.window.__V22_TEST__.getSession(),ids=s.items.map(i=>i.q.id);ok(ids.length&&new Set(ids).size===ids.length,'试卷出现重复题');ok(x.c.window.__V22_TEST__.duplicateGroups.every(g=>g.filter(id=>ids.includes(id)).length<2),'重复题组进入同卷');let correct=0;for(let i=0;i<s.items.length;i++){let item=s.items[i],good=(i+round)%5!==0,e=x.c.window.HOS_ENHANCED_FILL[item.q.id]||x.c.window.HOS_PEDAGOGY.fillBank[item.q.id];item.timeMs=good?8000:35000;if(good){item.answer=item.renderType==='fill'?((e?.variants?.find(v=>v.key===item.fillVariantKey)||e)?.answers||item.q.answers).join('、'):item.q.type==='multiple'?[...item.q.answers]:item.q.answers[0];correct++}else item.answer=item.renderType==='fill'?'__WRONG__':(item.q.options.find(o=>!item.q.answers.includes(o))||'__WRONG__')}s.totalActiveMs=s.items.reduce((n,i)=>n+i.timeMs,0);x.c.window.submitExam();let rec=x.c.window.__V22_TEST__.getStore().history[0];ok(rec.score===Math.round(correct/s.items.length*100),'成绩计算错误');return {ids,session:s}}
let x=boot(),reports=[];
for(let i=0;i<10;i++){x.c.window.beginRealExam('real');let r=answerAndSubmit(x,i);let counts=r.session.items.reduce((m,z)=>(m[z.renderType]++,m),{single:0,multiple:0,judge:0,fill:0});ok(JSON.stringify(counts)===JSON.stringify({single:15,multiple:10,judge:10,fill:10}),'真实考试不是15+10+10+10');reports.push('真实考试')}
for(let i=0;i<5;i++){x.c.window.beginExam('mixed');let r=answerAndSubmit(x,i+20);ok(r.ids.length===30,'普通模拟不是30题');reports.push('普通模拟')}
for(let i=0;i<5;i++){x.c.window.startSprint();let r=answerAndSubmit(x,i+40);ok(r.ids.length===30,'冲刺不是30题');ok(x.main.innerHTML.includes('冲刺结论')&&x.main.innerHTML.includes('仍需重点复习'),'冲刺结果缺少风险总结');reports.push('考前冲刺')}
let old=boot(JSON.stringify({schemaVersion:1,favorites:[4],wrong:{5:{count:2}},learning:{6:{attempts:3,correct:2,totalMs:90000,timedAttempts:3}},history:[],settings:{theme:'dark'}}));let migrated=JSON.parse(old.store.shenrenliu_qbank_v1);ok(migrated.favorites.includes(4)&&migrated.wrong['5'].count===2&&migrated.learning['6'].timedAttempts===3&&migrated.settings.theme==='dark','旧数据迁移丢失');
let damaged=boot('{bad json');ok(damaged.store.shenrenliu_qbank_v1_corrupt_backup==='{bad json','损坏JSON未保留副本');
let reminder=boot(JSON.stringify({schemaVersion:2,aggregateStats:{totalAnswers:30},settings:{lastBackup:0}}));ok(reminder.c.window.__V22_TEST__.backupReminder().includes('立即备份'),'产生学习数据后未出现备份提醒');
console.log(`v2.2.1稳定性回归通过：${reports.length}场（真实考试10、普通模拟5、考前冲刺5）；旧数据迁移、损坏JSON隔离、备份提醒均通过。`);
