const fs=require('fs'),vm=require('vm');
function cl(){const s=new Set();return {add:k=>s.add(k),remove:k=>s.delete(k),toggle(k,on){on?s.add(k):s.delete(k)},contains:k=>s.has(k)}}
function boot(initial=''){const main={innerHTML:''},watermark={textContent:''},store={shenrenliu_qbank_v1:initial},controls={'#realExamRule':{value:'normal'}};const document={hidden:false,documentElement:{dataset:{}},body:{classList:cl(),append(){}},querySelector:s=>s==='#main'?main:s==='#watermark'?watermark:controls[s]||null,querySelectorAll:()=>[],addEventListener(){},createElement(){return {style:{},classList:cl(),append(){},remove(){},click(){},select(){}}},execCommand(){return true}};const localStorage={getItem:k=>store[k]||null,setItem:(k,v)=>store[k]=v};const c={window:{addEventListener(){},matchMedia:()=>({matches:false}),scrollTo(){},scrollY:0,isSecureContext:false},document,localStorage,location:{protocol:'file:',href:'file:///test'},navigator:{},history:{pushState(){},replaceState(){}},performance:{now:()=>1000},requestAnimationFrame:f=>f(),setTimeout:()=>0,clearTimeout(){},setInterval:()=>0,clearInterval(){},structuredClone:o=>JSON.parse(JSON.stringify(o)),confirm:()=>true,prompt(){},alert(){},Blob:function(){},URL:{createObjectURL:()=>'',revokeObjectURL(){}},FileReader:function(){}};Object.assign(c.window,{window:c.window,document,localStorage,location:c.location,navigator:c.navigator});vm.createContext(c);for(const f of ['questions.js','pedagogy.js','enhanced-fill.js','app.js'])vm.runInContext(fs.readFileSync(f,'utf8'),c,{filename:f});return {c,store}}
function assert(v,m){if(!v)throw Error(m)}
const x=boot(),papers=[],groups=x.c.window.__V22_TEST__.duplicateGroups,typeCounts=[],fillExposure={},regularExposure={};let scoreChecks=0;
for(let round=0;round<150;round++){
  x.c.window.beginRealExam('real');const s=x.c.window.__V22_TEST__.getSession(),ids=s.items.map(i=>i.q.id),counts={single:0,multiple:0,judge:0,fill:0};assert(ids.length===45&&new Set(ids).size===45,`第${round+1}场题量或单卷重复异常`);assert(groups.every(g=>g.filter(id=>ids.includes(id)).length<2),`第${round+1}场重复题组冲突`);
  let correct=0,total=0;for(let i=0;i<s.items.length;i++){const item=s.items[i],willCorrect=((round*47+i*19)%10)<7;counts[item.renderType]++;item.timeMs=5000+((round*31+i*17)%76)*1000;total+=item.timeMs;if(willCorrect){let e=x.c.window.HOS_ENHANCED_FILL[item.q.id]||x.c.window.HOS_PEDAGOGY.fillBank[item.q.id];item.answer=item.renderType==='fill'?((e?.variants?.find(v=>v.key===item.fillVariantKey)||e)?.answers||item.q.answers).join('、'):item.q.type==='multiple'?[...item.q.answers]:item.q.answers[0];correct++}else item.answer=item.renderType==='fill'?'__WRONG__':(item.q.options.find(o=>!item.q.answers.includes(o))||'__WRONG__');(item.renderType==='fill'?fillExposure:regularExposure)[item.q.id]=((item.renderType==='fill'?fillExposure:regularExposure)[item.q.id]||0)+1}s.totalActiveMs=total;papers.push(ids);typeCounts.push(counts);x.c.window.submitExam();let rec=x.c.window.__V22_TEST__.getStore().history[0];assert(rec.score===Math.round(correct/45*100),`第${round+1}场随机错答得分错误`);scoreChecks++;
}
const st=x.c.window.__V22_TEST__.getStore(),usage=Object.values(st.examRotation.usage),covered=usage.length,overlaps={};for(let d=1;d<=10;d++){let vals=[];for(let i=d;i<papers.length;i++){let a=new Set(papers[i]);vals.push(papers[i-d].filter(id=>a.has(id)).length)}overlaps[d]={avg:Number((vals.reduce((a,b)=>a+b,0)/vals.length).toFixed(3)),max:Math.max(...vals)}}
assert(typeCounts.every(c=>c.single===15&&c.multiple===10&&c.judge===10&&c.fill===10),'题型结构异常');assert(covered===507,'150场未覆盖507题');assert(st.history.length===50&&st.aggregateStats.totalExams===150&&st.examRotation.round===150,'history/aggregate/rotation写入异常');
const last=x.c.window.__V22_TEST__.getSession();x.c.window.beginRealExam('real');x.c.window.chooseOption(0);const restored=boot(x.store.shenrenliu_qbank_v1);restored.c.window.resumeLastSession();assert(restored.c.window.__V22_TEST__.getSession().items[0].answer!=null,'断点恢复抽查失败');
const report={totalRounds:150,totalQuestionSlots:6750,coverage:`${covered}/507`,coverageRate:`${(covered/507*100).toFixed(2)}%`,paperTypeCounts:{single:15,multiple:10,judge:10,fill:10},duplicateWithinPaper:0,duplicateGroupConflicts:0,exposure:{min:Math.min(...usage),max:Math.max(...usage),avg:Number((usage.reduce((a,b)=>a+b,0)/usage.length).toFixed(3))},fillExposure:{questions:Object.keys(fillExposure).length,total:Object.values(fillExposure).reduce((a,b)=>a+b,0)},regularExposure:{questions:Object.keys(regularExposure).length,total:Object.values(regularExposure).reduce((a,b)=>a+b,0)},distanceOverlap:overlaps,historyRecords:st.history.length,rotationRound:st.examRotation.round,aggregateExams:st.aggregateStats.totalExams,scoreChecks,resumeSpotCheck:'passed',storageBytes:Buffer.byteLength(x.store.shenrenliu_qbank_v1,'utf8')};fs.writeFileSync('v2.2_150场压力测试报告.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
