const assert=require('assert/strict'),fs=require('fs'),{boot}=require('./scripts/test-app-harness.cjs');
const json=x=>JSON.parse(JSON.stringify(x));
(async()=>{
for(const type of ['single','multiple','judge','fill']){let x=boot();x.w.$('#specialType').value=type;x.w.startSpecialRecite();assert(!x.main.innerHTML.includes('class="explanation"'));assert(!x.main.innerHTML.includes('class="fill-study-answer"'));let s=x.t.getSession(),id=s.items[0].q.id;x.w.revealReciteAnswer();assert(x.main.innerHTML.includes('class="explanation"'));assert(!s.items[0].attemptRecorded);x.w.nextQ();assert(!x.main.innerHTML.includes('class="explanation"'));x.w.setReciteAnswerMode('always');assert(x.main.innerHTML.includes('class="explanation"'));x.w.nextQ();assert(x.main.innerHTML.includes('class="explanation"'));x.w.setReciteAnswerMode('manual');assert(!x.main.innerHTML.includes('class="explanation"'));assert.equal(x.t.getStore().aggregateStats.totalAnswers,0);if(type==='fill'){assert.equal(s.items.length,208);assert.equal(s.items[0].checked,false);assert.equal(x.t.getStore().learning[id].attempts,0)}}
let x=boot();assert.equal(x.t.getStore().settings.allModesOpen,false);x.w.rememberModesOpen(true);x.w.startStudy();x.w.navHome(true);assert(x.main.innerHTML.includes('panel" open ontoggle'));let reload=boot(JSON.parse(x.store.shenrenliu_qbank_v1));assert(reload.t.getStore().settings.allModesOpen);reload.w.rememberModesOpen(false);assert.equal(reload.t.getStore().settings.allModesOpen,false);
x=boot({settings:{quickEntryMigration:'quick-entry-migrated-v2.2.9-fengshen-r3',homeShortcuts:['balanced','search','sequence','review'],quickEntryCustomized:true}});assert(!x.main.innerHTML.includes('全库均衡复习'));assert(x.t.getStore().settings.homeShortcuts.includes('today'));
x.w.renderSpecialSetup('exam','fill','standard');assert(!x.main.innerHTML.includes('填空难度'));assert(x.main.innerHTML.includes('统一填空题库 · 208题'));x.w.$('#specialType').value='fill';x.w.$('#countBtns .active').dataset.n='208';x.w.beginSpecialExam();assert.equal(x.t.getSession().items.length,208);assert(x.t.getSession().items.every(i=>i.fillLevel==='enhanced'));assert.equal(new Set(x.t.getSession().items.map(i=>i.q.id)).size,208);
for(const kind of ['fav','wrong']){x=boot({favorites:[12,13,171],wrong:{12:{count:2},13:{count:1},171:{count:1}}});x.w.renderCollectionExamSetup(kind);x.w.$('#collectionCount').value='2';x.w.beginCollectionExam(kind);let s=x.t.getSession();assert.equal(s.items.length,2);assert(s.items.every(i=>[12,13,171].includes(i.q.id)));assert(!x.main.innerHTML.includes('class="explanation"'));x.w.submitExam();assert.equal(x.t.getStore().history[0].count,2);assert.equal(x.t.getStore().history[0].score,0);x.w.navHome(true);x.w.beginCollectionExam(kind,true);assert.equal(x.t.getSession().items.length,3);let saved=json(x.t.getStore().lastSession);reload=boot(JSON.parse(x.store.shenrenliu_qbank_v1));reload.w.resumeLastSession();assert.deepEqual(json(reload.t.getSession().items.map(i=>i.q.id)),saved.ids)}
x=boot({favorites:[12]});x.w.renderCollectionExamSetup('fav');x.w.$('#collectionCount').value='2';x.w.beginCollectionExam('fav');assert.equal(x.t.getSession(),null);x.w.$('#collectionCount').value='0';x.w.beginCollectionExam('fav');assert.equal(x.t.getSession(),null);
x=boot();x.c.navigator.userAgent='Mozilla/5.0 (Linux; Android 13) HuaweiBrowser/15';x.w.PWA_INSTALL={state:{prompt:{}},promptInstall:async()=> 'dismissed',inspectManifest:()=>{}};await x.w.installApp();assert(!x.nodes['#installModal'].classList.contains('hidden'));assert(x.nodes['#installGuideBody'].innerHTML.includes('桌面'));assert(!fs.readFileSync('app.js','utf8').includes('已取消安装，可稍后从浏览器菜单安装'));x.w.showInstallGuide('ios');assert(x.nodes['#installGuideBody'].innerHTML.includes('Safari'));x.w.showInstallGuide('android');assert(x.nodes['#installGuideBody'].innerHTML.includes('不一定支持'));
Object.assign(x.c,{TextEncoder,TextDecoder,Uint8Array,Blob,CompressionStream:undefined,DecompressionStream:undefined,btoa,atob});x.w.openTransfer();await x.w.generateTransferCode();let code=x.nodes['#transferOutput'].value;assert(code.startsWith('SLQ1.C.'));assert.deepEqual(json(await x.w.QBANK_TRANSFER.decode(code)),json(x.w.QBANK_TRANSFER.makeLite(x.t.getStore(),(await x.w.QBANK_TRANSFER.decode(code)).createdAt)));
// Old raw/gzip codes remain readable; compact schema rejects duplicate IDs.
const data=x.w.QBANK_TRANSFER.makeLite(x.t.getStore()),old=await x.w.QBANK_TRANSFER.encode(data,false);assert(old.startsWith('SLQ1.R.'));assert.deepEqual(json(await x.w.QBANK_TRANSFER.decode(old)),json(data));
console.log('七项体验精修通过：背诵手动/常显/零答题污染、208全题、展开记忆、入口兼容、收藏错题抽题/全部/判分/恢复、移动安装失败指引、无压缩兼容码与旧码读取。');
})().catch(e=>{console.error(e);process.exitCode=1});
