const assert=require('assert/strict'),fs=require('fs'),crypto=require('crypto');
const {boot}=require('./scripts/test-app-harness.cjs');
const eq=(a,b,msg)=>assert.equal(JSON.stringify(a),JSON.stringify(b),msg);
let x=boot();x.w.beginRealExam('fillStrong');let paper=x.t.getSession();
assert(paper.items.every(i=>i.presentationSnapshot),'必须在创建会话时保存全部呈现快照');
for(const i of paper.items){i.answer=i.renderType==='fill'?i.presentationSnapshot.correctAnswer.join('、'):i.q.type==='multiple'?[...i.q.answers]:i.q.answers[0];i.timeMs=1000}
const wrong=paper.items.find(i=>i.renderType==='fill'&&i.q.type==='single'),multi=paper.items.find(i=>i.renderType==='fill'&&i.q.type==='multiple');
// Guarantee both source categories even if this random exam did not pick one.
const entries=Object.entries(x.w.HOS_ENHANCED_FILL),bank=x.w.QUESTION_BANK;
for(const type of ['single','multiple']){const q=bank.find(q=>q.type===type&&entries.some(([id])=>Number(id)===q.id));let item=paper.items.find(i=>i.q.id===q.id);if(!item||item.renderType!=='fill'){x.w.startFillStudy('sequence','enhanced');item=x.t.getSession().items.find(i=>i.q.id===q.id)}const snapshot=JSON.parse(JSON.stringify(item.presentationSnapshot));x.t.startReviewRecords([{questionId:q.id,presentationSnapshot:snapshot,userAnswer:'错误答案'}],'测试复盘');let s=x.t.getSession(),actual=s.items[0];assert.equal(actual.renderType,'fill');eq(actual.presentationSnapshot,snapshot);assert(x.main.innerHTML.includes('本场题型'));const key=actual.fillVariantKey,stem=x.t.itemStem(actual);actual.answer='输入中的答案';x.w.setReviewMode('original');assert.equal(s.items[0].renderType,q.type);assert.equal(s.items[0].attemptRecorded,true);x.w.setReviewMode('presented');assert.equal(s.items[0],actual);assert.equal(actual.answer,'输入中的答案');assert.equal(x.t.itemStem(actual),stem);assert.equal(actual.fillVariantKey,key);actual.answer=x.t.itemAnswers(actual).join('、');assert(x.t.answerCorrect(actual,actual.answer));x.w.checkStudy();const attempts=x.t.getStore().learning[q.id].attempts;for(let k=0;k<12;k++){x.w.setReviewMode('original');x.w.setReviewMode('presented')}assert.equal(x.t.getStore().learning[q.id].attempts,attempts,'切换重复统计');}
// Every dynamic variant survives capture, serialization, restoration and mode switching.
let variants=0;
for(const [id,e] of entries)for(const v of e.variants||[]){const q=bank.find(q=>q.id===Number(id)),item={q,renderType:'fill',fillLevel:'enhanced',fillVariantKey:v.key,optionOrder:[...q.options],answer:null};const snapshot=x.t.capturePresentation(item);x.t.startReviewRecords([{questionId:q.id,presentationSnapshot:JSON.parse(JSON.stringify(snapshot))}],'动态复盘');const before=x.t.getSession().items[0];eq(x.t.itemAnswers(before),v.answers);x.w.setReviewMode('original');x.w.setReviewMode('presented');eq(x.t.getSession().items[0].presentationSnapshot,snapshot);variants++;}assert.equal(variants,60);
// Wrong+slow appears only in wrong; wrong queue remains ahead of correct slow.
x=boot();x.w.beginRealExam('fillStrong');paper=x.t.getSession();for(const i of paper.items){i.answer=i.renderType==='fill'?x.t.itemAnswers(i).join('、'):i.q.type==='multiple'?[...i.q.answers]:i.q.answers[0];i.timeMs=1000}
paper.items[0].answer=null;paper.items[0].timeMs=180000;paper.items[1].timeMs=180000;x.w.submitExam();
let groups=x.t.sessionReviewGroups(paper.items);assert.equal(groups.wrong.length,1);assert(!groups.slow.includes(paper.items[0]));assert(groups.high.includes(paper.items[1]));assert.equal(groups.queue[0],paper.items[0]);assert.equal(new Set(groups.queue.map(i=>i.q.id)).size,groups.queue.length);
let html=x.main.innerHTML;assert(html.indexOf('<h2>本场错题')<html.indexOf('<h2>高耗时 / 最慢题'));assert(html.indexOf('<h2>高耗时 / 最慢题')<html.indexOf('<h2>⏱ 用时分析'));const slowBlock=html.split('<h2>高耗时 / 最慢题')[1].split('⏱ 用时分析')[0];assert(!slowBlock.includes('#'+paper.items[0].q.id+' '));
let packed=JSON.parse(x.store.shenrenliu_qbank_v1);assert(packed.presentationCatalog.length>0);let store=x.t.unpackStore(packed),saved=store.history[0];assert.equal(saved.presentationSnapshots.length,55);assert.equal(saved.userAnswers[0],null);eq(x.t.unpackStore(JSON.parse(x.t.packStore(store))),store);
let reloaded=boot(packed);reloaded.w.reviewHistoryPaper(0);eq(reloaded.t.getSession().items.map(i=>i.presentationSnapshot),saved.presentationSnapshots,'重载后快照丢失');let fifty={...store,history:Array.from({length:50},()=>saved)};assert(x.t.packStore(fifty).length<JSON.stringify(fifty).length*.8,'重复快照没有节省空间');
const expected=saved.presentationSnapshots[0];x.w.reviewCurrentQuestion(paper.items[0].q.id);eq(x.t.getSession().items[0].presentationSnapshot,expected);
reloaded.w.redoHistoryPaper(0);eq(reloaded.t.getSession().items.map(i=>i.presentationSnapshot),saved.presentationSnapshots);
reloaded.w.resumeLastSession();eq(reloaded.t.getSession().items.map(i=>i.presentationSnapshot),saved.presentationSnapshots);
let wrongId=paper.items[0].q.id;reloaded.w.startWrongCategory('all');eq(reloaded.t.getSession().items[0].presentationSnapshot,store.wrong[wrongId].lastPresentation);
for(const records of [[{...paper.items[1],correct:true,timeMs:180000},{...paper.items[2],correct:true,timeMs:1000}],[{...paper.items[0],correct:false,timeMs:0}]]){const g=x.t.sessionReviewGroups(records);assert.equal(new Set(g.queue.map(i=>i.q.id)).size,g.queue.length)}
// Legacy history cannot infer a presented form from renderTypes/variant keys alone.
const legacy=JSON.parse(JSON.stringify(saved));delete legacy.presentationSnapshots;reloaded=boot({history:[legacy]});reloaded.w.reviewHistoryPaper(0);assert(reloaded.t.getSession().items.every(i=>i.renderType===i.q.type&&i.legacyReview));reloaded.w.redoHistoryPaper(0);assert(reloaded.t.getSession().items.every(i=>i.renderType===i.q.type));assert.equal(reloaded.t.getStore().history.length,1);
const judge=bank.find(q=>q.type==='judge');reloaded.w.startStudy('sequence',[judge]);const p=reloaded.t.capturePresentation(reloaded.t.getSession().items[0]);reloaded.t.startReviewRecords([{questionId:judge.id,presentationSnapshot:p}],'判断复盘');assert.equal(reloaded.t.getSession().items[0].renderType,'judge');
reloaded.w.startFillStudy('sequence','standard');const standard=reloaded.t.getSession().items[0],sp=JSON.parse(JSON.stringify(standard.presentationSnapshot));reloaded.t.startReviewRecords([{questionId:standard.q.id,presentationSnapshot:sp}],'标准填空复盘');assert.equal(reloaded.t.getSession().items[0].renderType,'fill');eq(reloaded.t.getSession().items[0].presentationSnapshot,sp);
const ancient=boot({history:[{ids:[judge.id],count:1,score:0}]});assert.equal(ancient.t.getStore().history[0].paperDamaged,false);ancient.w.reviewHistoryPaper(0);assert.equal(ancient.t.getSession().items[0].renderType,'judge');
const svg=fs.readFileSync('icon-source.svg','utf8');assert(svg.includes('<path'));assert(!svg.includes('<text'),'图标依赖系统字体');assert(svg.includes('劉'));assert(!fs.readFileSync('index.html','utf8').includes('brand-badge">刘'));
for(const n of [16,32,48,64,128,192,256,512]){let png=fs.readFileSync(`icon-${n}.png`);assert.equal(png.readUInt32BE(16),n);assert.equal(png.readUInt32BE(20),n)}
assert(JSON.parse(fs.readFileSync('manifest.webmanifest')).icons.every(i=>i.src.endsWith('?v=2.2.9-fengshen-r8')));
console.log('v2.2.8回归通过：创建时全卷快照、单/多选转填空、判断、60变体不重抽、12次题型切换不重复统计、错慢去重及顺序、历史重载/重做/断点/错题本恢复、旧历史原题回退、8尺寸劉字矢量图标。');
