const assert=require('assert/strict'),fs=require('fs'),{boot}=require('./scripts/test-app-harness.cjs');
const equal=(a,b)=>assert.equal(JSON.stringify(a),JSON.stringify(b)),key='quick-entry-migrated-v2.2.9-fengshen-r3',defaults=['fillStrong','real','today','random'];
for(const config of [{}, {homeShortcuts:['search','wrong','favorites','sequence'],quickEntryCustomized:true}, {homeShortcuts:['fillStrong','real','random','wrong'],quickEntryCustomized:false}]){
let x=boot({settings:config});equal(x.t.getStore().settings.homeShortcuts,defaults);assert.equal(x.store[key],'1');assert.equal(x.t.getStore().settings.quickEntryMigration,key);
let raw=JSON.parse(x.store.shenrenliu_qbank_v1);raw.settings.homeShortcuts=['sequence','review','balanced','search'];raw.settings.quickEntryCustomized=true;let y=boot(raw);equal(y.t.getStore().settings.homeShortcuts,raw.settings.homeShortcuts);assert.equal(y.store[key],'1');
}
let x=boot(),catalog=x.w.__V22_TEST__.shortcutCatalog,more=x.main.innerHTML.match(/<details class="more-modes[\s\S]*?<\/details>/)[0];assert(more.includes('所有训练模式'));assert(!more.includes('更多训练模式'));for(const item of catalog){assert(more.includes('<h3>'+item.title+'</h3>'));const name=item.action.match(/^([A-Za-z_$][\w$]*)\(/)[1];assert.equal(typeof x.w[name],'function',item.title+'入口目标丢失')}
assert.equal(catalog.length,12);assert(!catalog.some(i=>['sprint','mixedExam','technical','enhancedFillStudy','enhancedFillExam'].includes(i.id)));assert(x.main.innerHTML.includes('personal-entry'));assert(!x.main.innerHTML.includes('sprint-entry'));
x.w.renderTodayReviewSetup();assert(x.main.innerHTML.includes('startTodayReview()'));assert(x.main.innerHTML.includes('renderSprintSetup()'));x.w.startTodayReview();assert.equal(x.t.getSession().title,'今日复习');x.w.navHome(true);x.w.renderSprintSetup();x.w.startSprint();assert.equal(x.t.getSession().mode,'sprint');
// Restoring an unanswered paper retains IDs, choices, type/blank snapshots and answers.
x=boot();x.w.beginRealExam('fillStrong');let session=x.t.getSession();session.items[0].answer=session.items[0].q.answers[0];session.items[0].timeMs=2000;x.w.toggleFav(session.items[0].q.id);x.w.toggleReviewFlag(session.items[0].q.id);x.w.jumpQ(4);let saved=x.t.getStore().lastSession,y=boot(JSON.parse(x.store.shenrenliu_qbank_v1));y.w.resumeLastSession();equal(y.t.getSession().items.map(i=>i.q.id),saved.ids);equal(y.t.getSession().items.map(i=>i.fillVariantKey||''),saved.fillVariantKeys);equal(y.t.getSession().items.map(i=>i.renderType),saved.renderTypes);equal(y.t.getSession().items.map(i=>i.answer),saved.answers);assert(y.main.innerHTML.includes('题号 5/55'));assert(y.t.getStore().favorites.includes(saved.ids[0]));assert(y.t.getStore().reviewFlags[saved.ids[0]]);
// Cancel preserves snapshot; confirmation removes active session too, so saving cannot resurrect it.
let before=y.t.getStore().history.length;y.c.confirm=()=>false;y.w.discardLastSession();assert(y.t.getStore().lastSession);y.c.confirm=()=>true;y.w.discardLastSession();assert.equal(y.t.getStore().lastSession,null);assert.equal(y.t.getSession(),null);y.t.saveSession();assert.equal(y.t.getStore().lastSession,null);assert.equal(y.t.getStore().history.length,before);assert(!y.main.innerHTML.includes('继续上次考试'));assert.equal(boot(JSON.parse(y.store.shenrenliu_qbank_v1)).t.getStore().lastSession,null);
y=boot(JSON.parse(x.store.shenrenliu_qbank_v1));let shown=0;y.w.$('#discardConfirm').showModal=()=>shown++;y.w.$('#discardConfirm').close=()=>{};y.w.discardLastSession();assert.equal(shown,1);y.w.cancelDiscardSession();assert(y.t.getStore().lastSession);y.w.discardLastSession();y.w.confirmDiscardSession();assert.equal(y.t.getStore().lastSession,null);
// Storage failures are explicit and do not falsely erase the pending paper in memory.
y=boot(JSON.parse(x.store.shenrenliu_qbank_v1));y.c.localStorage.setItem=()=>{throw Error('quota')};y.w.discardLastSession();assert(y.t.getStore().lastSession);
const app=fs.readFileSync('app.js','utf8'),html=fs.readFileSync('index.html','utf8');assert(html.includes('确认放弃')&&html.includes('取消'));assert(!app.includes('localStorage.clear'));assert(app.includes('prev.disabled=sourcePage<=1'));assert(app.includes('next.disabled=sourcePage>=111'));assert(app.includes('保存失败：'));assert(fs.readFileSync('sw.js','utf8').includes('fengshen-r4-${BUILD_VERSION}'));console.log('r3回归通过：一次性强制迁移/后续自定义、14入口全集与可调用目标、今日/冲刺独立算法入口、重点区域、完整恢复、取消/确认放弃及防重新保存、失败反馈、图页边界、新缓存。');
