const fs=require('fs'),vm=require('vm');
function classList(){const s=new Set();return {add:k=>s.add(k),remove:k=>s.delete(k),toggle(k,on){if(on===undefined)on=!s.has(k);on?s.add(k):s.delete(k)},contains:k=>s.has(k)}}
function boot(initialStore=''){
  const main={innerHTML:''},watermark={textContent:''},bodyCL=classList(),controls={'#realExamRule':{value:'normal'}},store={shenrenliu_qbank_v1:initialStore};let clock=1000;
  const document={hidden:false,documentElement:{dataset:{}},body:{classList:bodyCL,append(){}},querySelector(s){return s==='#main'?main:s==='#watermark'?watermark:controls[s]||null},querySelectorAll:()=>[],addEventListener(){},createElement(){return {style:{},classList:classList(),append(){},remove(){},click(){},select(){}}},execCommand(){return true}};
  const localStorage={getItem:k=>store[k]||null,setItem:(k,v)=>store[k]=v};
  const c={window:{addEventListener(){},matchMedia:()=>({matches:false}),scrollTo(){},scrollY:0,isSecureContext:false},document,localStorage,location:{protocol:'file:',href:'file:///test'},navigator:{},history:{pushState(){},replaceState(){}},performance:{now:()=>clock},requestAnimationFrame:f=>f(),setTimeout:()=>0,clearTimeout(){},setInterval:()=>0,clearInterval(){},structuredClone:o=>JSON.parse(JSON.stringify(o)),confirm:()=>true,prompt(){},alert(){},Blob:function(){},URL:{createObjectURL:()=>'',revokeObjectURL(){}},FileReader:function(){}};
  Object.assign(c.window,{window:c.window,document,localStorage,location:c.location,navigator:c.navigator});vm.createContext(c);for(const f of ['questions.js','pedagogy.js','enhanced-fill.js','app.js'])vm.runInContext(fs.readFileSync(f,'utf8'),c,{filename:f});return {c,store,setClock:v=>clock=v};
}
function ok(v,m){if(!v)throw Error(m)}
let x=boot();x.c.window.startStudy('sequence',[x.c.window.QUESTION_BANK[0]]);let s=x.c.window.__V22_TEST__.getSession(),id=s.items[0].q.id;x.c.window.showAnswer();ok(!x.c.window.__V22_TEST__.getStore().learning[id]?.attempts,'直接看答案被记为attempt');x.c.window.checkStudy();ok(x.c.window.__V22_TEST__.getStore().learning[id].assistedCorrect===1,'看答案后答对未标记辅助');x.c.window.checkStudy();ok(x.c.window.__V22_TEST__.getStore().learning[id].attempts===1,'同题产生重复attempt');
x=boot();let q=x.c.window.QUESTION_BANK.find(q=>q.type==='single'&&q.options.some(o=>!q.answers.includes(o)));x.c.window.startStudy('sequence',[q]);s=x.c.window.__V22_TEST__.getSession();let wrong=s.items[0].optionOrder.findIndex(o=>!q.answers.includes(o));x.c.window.chooseOption(wrong);x.setClock(6000);x.c.window.checkStudy();let before=x.c.window.__V22_TEST__.getStore();ok(before.wrong[q.id].count>0,'答错未进错题');x.c.window.showAnswer();let after=x.c.window.__V22_TEST__.getStore();ok(after.wrong[q.id].count===before.wrong[q.id].count&&after.learning[q.id].attempts===1,'答错后看答案污染错题或attempt');ok(after.learning[q.id].timedAttempts===1&&after.learning[q.id].totalMs>=5000,'学习真实用时未记录');
x=boot();q=x.c.window.QUESTION_BANK.find(q=>q.type==='single');x.c.window.startStudy('sequence',[q]);x.c.window.showExplanation();s=x.c.window.__V22_TEST__.getSession();x.c.window.chooseOption(s.items[0].optionOrder.indexOf(q.answers[0]));x.setClock(4500);x.c.window.checkStudy();after=x.c.window.__V22_TEST__.getStore();ok(after.learning[q.id].assistedCorrect===1&&after.learning[q.id].streak===0,'先看解析后答对被算作独立正确');
x=boot();x.c.window.beginRealExam('real');s=x.c.window.__V22_TEST__.getSession();let groups=x.c.window.__V22_TEST__.duplicateGroups,ids=new Set(s.items.map(i=>i.q.id));ok(groups.every(g=>g.filter(id=>ids.has(id)).length<2),'同duplicateGroup进入同卷');let savedOrder=JSON.stringify(s.items.map(i=>i.optionOrder));x.c.window.__V22_TEST__.flush();let y=boot(x.store.shenrenliu_qbank_v1);y.c.window.resumeLastSession();ok(JSON.stringify(y.c.window.__V22_TEST__.getSession().items.map(i=>i.optionOrder))===savedOrder,'选项顺序刷新恢复后变化');
console.log('v2.2学习逻辑校验通过：答案/解析不污染、单流程单attempt、错题保护、真实计时、重复组隔离、选项顺序恢复一致。');
