const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');const {boot}=require('./scripts/test-app-harness.cjs');
const equal=(a,b)=>assert.equal(JSON.stringify(a),JSON.stringify(b));
function paper(){let x=boot();x.w.beginRealExam('fillStrong');return x}
function correct(item){return item.renderType==='fill'?item.presentationSnapshot.correctAnswer.join('、'):item.q.type==='multiple'?[...item.q.answers]:item.q.answers[0]}
// Every unanswered representation is allowed in normal mode and stored as null.
let x=paper(),s=x.t.getSession(),confirmation='';x.c.confirm=message=>(confirmation=message,true);for(let i=0;i<s.items.length;i++){s.items[i].answer=[null,'',' \t\n　',[],['',' ']][i%5];s.items[i].timeMs=1000}x.w.submitExam();assert(confirmation.includes('55'));assert.equal(s.finished,true);let rec=x.t.getStore().history[0];assert.equal(rec.score,0);assert.equal(rec.correct,0);assert(rec.userAnswers.every(a=>a===null));assert(rec.questionTimes.every(r=>!r.answered&&!r.correct));assert.equal(Object.keys(x.t.getStore().wrong).length,55);assert.equal((x.main.innerHTML.match(/你的答案：未作答/g)||[]).length,55);x.w.submitExam();assert.equal(x.t.getStore().history.length,1);
x=paper();s=x.t.getSession();s.items.forEach(i=>{i.answer=correct(i);i.timeMs=1000});const blank=[s.items.find(i=>i.renderType==='single'),s.items.find(i=>i.renderType==='multiple'),s.items.find(i=>i.renderType==='judge'),...s.items.filter(i=>i.renderType==='fill').slice(0,5)];blank.forEach(i=>i.answer='   ');x.c.confirm=message=>(assert(message.includes('8')),true);x.w.submitExam();rec=x.t.getStore().history[0];assert.equal(rec.correct,47);assert.equal(rec.score,85);assert.equal(rec.questionTimes.filter(i=>!i.answered).length,8);assert(blank.every(i=>i.answer===null));assert(x.main.innerHTML.indexOf('本场错题 / 未答题')<x.main.innerHTML.indexOf('高耗时 / 最慢题'));x.w.retryWrongCurrent();assert.equal(x.t.getSession().items.length,8);assert(x.main.innerHTML.includes('本场作答：未作答'));
x=paper();s=x.t.getSession();const partial=s.items.find(i=>i.renderType==='fill'&&i.presentationSnapshot.correctAnswer.length>1);assert(partial);partial.answer=partial.presentationSnapshot.correctAnswer[0];x.w.submitExam();rec=x.t.getStore().history[0];assert.equal(rec.questionTimes.filter(r=>r.answered).length,1);assert.equal(partial.answer,partial.presentationSnapshot.correctAnswer[0]);assert.equal(partial.correct,false);
x=paper();s=x.t.getSession();s.strict=true;s.items.forEach(i=>i.answer=' \n ');x.w.submitExam();assert(!s.finished);assert.equal(x.t.getStore().history.length,0);s.items.forEach(i=>i.answer=correct(i));x.w.submitExam();assert(s.finished);assert.equal(x.t.getStore().history[0].score,100);
x=paper();s=x.t.getSession();x.c.confirm=()=>false;x.w.submitExam();assert(!s.finished);assert.equal(x.t.getStore().history.length,0);x.c.confirm=()=>true;x.w.submitExam();assert(s.finished);
// Real dialog route: cancellation/confirmation are separate, not native validation.
x=paper();s=x.t.getSession();let shown=0,closed=0;x.w.$('#submitConfirm').showModal=()=>shown++;x.w.$('#submitConfirm').close=()=>closed++;x.w.submitExam();assert.equal(shown,1);assert(s.pendingSubmission);assert(!s.finished);x.w.cancelExamSubmit();assert(!s.pendingSubmission);assert(!s.finished);x.w.submitExam();x.w.confirmExamSubmit();assert(s.finished);assert.equal(x.t.getStore().history[0].correct,0);assert.equal(closed,2);
const html=fs.readFileSync('index.html','utf8'),app=fs.readFileSync('app.js','utf8');assert(html.indexOf('src="pwa-install.js?v=2.2.9-fengshen-r5"')<html.indexOf('rel="manifest"'));assert(html.indexOf('src="pwa-install.js?v=2.2.9-fengshen-r5"')<html.indexOf('src="questions.js"'));assert(!/\b(?:textarea|input)[^>]+required/.test(app));assert(!html.includes('location.reload()'),'旧的无条件更新刷新仍存在');assert(html.includes('继续答题')&&html.includes('确认交卷'));
const manifest=JSON.parse(fs.readFileSync('manifest.webmanifest'));const url=new URL('https://example.test/shenrenliu-qbank/manifest.webmanifest?v=2.2.9');assert.equal(new URL(manifest.id,url.origin+'/').pathname,'/shenrenliu-qbank/');assert.equal(new URL(manifest.start_url,url).pathname,'/shenrenliu-qbank/');assert.equal(new URL(manifest.scope,url).pathname,'/shenrenliu-qbank/');
const source=fs.readFileSync('pwa-install.js','utf8');
function pwa(){let events={},domEvents={},reloads=0,posted=[],prompts=0;const loc={protocol:'https:',origin:url.origin,pathname:'/shenrenliu-qbank/',href:'https://example.test/shenrenliu-qbank/',reload:()=>reloads++},registration={active:{},waiting:{postMessage:x=>posted.push(x)},addEventListener(){},update:async()=>{}},nav={serviceWorker:{controller:null,addEventListener:(k,f)=>events[k]=f,register:async(u,o)=>{assert(u.endsWith('/shenrenliu-qbank/sw.js'));assert(o.scope.endsWith('/shenrenliu-qbank/'));return registration},ready:Promise.resolve(registration)}},media={matches:false,addEventListener(){}};const w={addEventListener:(k,f)=>events[k]=f,matchMedia:()=>media,canReloadForPwaUpdate:()=>true},document={readyState:'loading',baseURI:loc.href,addEventListener:(k,f)=>domEvents[k]=f,querySelector:()=>({href:url.href})};let c={window:w,document,navigator:nav,location:loc,URL,Uint8Array,DataView,fetch:async u=>{u=new URL(u);if(u.pathname.endsWith('.webmanifest'))return {ok:true,headers:{get:()=> 'application/manifest+json'},json:async()=>manifest};const size=u.pathname.includes('192')?192:512,b=fs.readFileSync(`icon-${size}.png`);return {ok:true,headers:{get:()=> 'image/png'},arrayBuffer:async()=>b.buffer.slice(b.byteOffset,b.byteOffset+b.byteLength)}}};vm.createContext(c);vm.runInContext(source,c);return {w,nav,events,domEvents,media,posted,reloads:()=>reloads,registration,event:(outcome='accepted')=>({preventDefault(){},prompt:async()=>prompts++,userChoice:Promise.resolve({outcome})}),prompts:()=>prompts}}
(async()=>{let p=pwa();assert(p.events.beforeinstallprompt&&p.events.appinstalled,'head脚本没有立即监听');p.events.beforeinstallprompt(p.event());assert(p.w.PWA_INSTALL.state.prompt);assert.equal(await p.w.PWA_INSTALL.promptInstall(),'accepted');assert.equal(p.prompts(),1);assert.equal(p.w.PWA_INSTALL.state.prompt,null);p.events.appinstalled();assert(p.w.PWA_INSTALL.state.installed);assert.equal(await p.w.PWA_INSTALL.promptInstall(),'installed');p.events.beforeinstallprompt(p.event('dismissed'));assert.equal(await p.w.PWA_INSTALL.promptInstall(),'dismissed');p.events.beforeinstallprompt(p.event());p.media.matches=true;assert.equal(await p.w.PWA_INSTALL.promptInstall(),'installed');p.media.matches=false;assert(await p.w.PWA_INSTALL.inspectManifest());assert.equal(p.w.PWA_INSTALL.state.manifest.scope,url.origin+'/shenrenliu-qbank/');p.domEvents.DOMContentLoaded();await new Promise(r=>setImmediate(r));assert.equal(p.w.PWA_INSTALL.state.controlled,false,'ready误当作受控');p.nav.serviceWorker.controller={scriptURL:url.origin+'/shenrenliu-qbank/sw.js'};p.events.controllerchange();assert.equal(p.w.PWA_INSTALL.state.controlled,true);assert.equal(p.reloads(),0,'更新自动刷新');p.w.canReloadForPwaUpdate=()=>false;assert.equal(p.w.PWA_INSTALL.requestUpdate(),false);assert.equal(p.posted.length,0);p.w.canReloadForPwaUpdate=()=>true;p.w.PWA_INSTALL.requestUpdate();equal(p.posted,['SKIP_WAITING']);p.events.controllerchange();assert.equal(p.reloads(),1);
const sw=fs.readFileSync('sw.js','utf8');assert(sw.includes('if (!self.registration?.active) await self.skipWaiting()'));assert(sw.includes('v2.2.9-fengshen-r5-${BUILD_VERSION}'));assert(!source.includes('localStorage'),'安装标记永久缓存导致卸载误报');console.log('v2.2.9回归通过：55题全空、47/55剩8题、四题型空白与纯空格/空数组、部分填空、严格模式、取消/确认/重复交卷、未答null及复盘、head早期安装事件/拒绝/安装后/再安装、真实manifest/PNG与子目录身份、SW控制与安全更新。');})().catch(e=>{console.error(e);process.exit(1)});
