const fs=require('fs'),vm=require('vm');
const main={innerHTML:''},watermark={textContent:''},realExamRule={value:'normal'},store={};
const bodyClasses=new Set(),classList={toggle(k,on){if(on===undefined)on=!bodyClasses.has(k);on?bodyClasses.add(k):bodyClasses.delete(k)},add(k){bodyClasses.add(k)},remove(k){bodyClasses.delete(k)}};
const document={hidden:false,documentElement:{dataset:{}},body:{classList,append(){}},querySelector:s=>s==='#main'?main:s==='#watermark'?watermark:s==='#realExamRule'?realExamRule:null,querySelectorAll:()=>[],addEventListener(){},createElement(){return {style:{},classList,append(){},remove(){},click(){},select(){}}},execCommand(){return true}};
const localStorage={getItem:k=>store[k]||null,setItem:(k,v)=>store[k]=v};
const context={window:{addEventListener(){},matchMedia:()=>({matches:false}),scrollTo(){},scrollY:0,isSecureContext:false},document,localStorage,location:{protocol:'file:',href:'file:///test'},navigator:{},history:{pushState(){},replaceState(){}},performance:{now:()=>0},requestAnimationFrame:f=>f(),setTimeout:()=>0,clearTimeout(){},setInterval:()=>0,clearInterval(){},structuredClone:o=>JSON.parse(JSON.stringify(o)),confirm:()=>true,prompt(){},alert(){},Blob:function(){},URL:{createObjectURL:()=>'',revokeObjectURL(){}},FileReader:function(){}};
context.window.window=context.window;context.window.document=document;context.window.localStorage=localStorage;context.window.location=context.location;context.window.navigator=context.navigator;vm.createContext(context);
for(const file of ['questions.js','pedagogy.js','enhanced-fill.js','app.js'])vm.runInContext(fs.readFileSync(file,'utf8'),context,{filename:file});
if(!main.innerHTML.includes('题库数据自检通过'))throw Error('首页题库自检未通过');
context.window.startStudy('sequence');
if(!main.innerHTML.includes('class="quick-nav"')||!main.innerHTML.includes('题号 1/507'))throw Error('快捷导航未正确显示');
context.window.nextQ();if(!main.innerHTML.includes('题号 2/507'))throw Error('下一题切换失败');
context.window.renderRealExamSetup();context.window.beginRealExam();
if(!main.innerHTML.includes('题号 1/55')||!main.innerHTML.includes('填空增强版真实模拟'))throw Error('55题真实模拟或考试快捷栏异常');
context.window.jumpQ(54);if(!main.innerHTML.includes('题号 55/55')||!main.innerHTML.includes('检查/交卷'))throw Error('末题交卷快捷按钮异常');
bodyClasses.add('sheet-open');context.window.submitExam();if(bodyClasses.has('sheet-open'))throw Error('移动端交卷后页面滚动锁未解除');
if(JSON.parse(store.shenrenliu_qbank_v1).examRotation.round!==1)throw Error('交卷后轮换记录未准确写入一次');
context.window.renderReviewList();if(!main.innerHTML.includes('待复核清单'))throw Error('错题/复核清单入口异常');
for(const name of ['toggleAnswerPanel','beginExam','beginRealExam','submitExam','renderReviewList'])if(typeof context.window[name]!=='function')throw Error(`${name}未正确导出`);
console.log('运行时校验通过：首页自检、背题、固定快捷栏、下一题切换、考试与错题入口均正常。');
