const assert=require('assert/strict'),fs=require('fs'),vm=require('vm'),{boot}=require('./scripts/test-app-harness.cjs');const json=x=>JSON.parse(JSON.stringify(x));
const x=boot({favorites:[12],mastery:{171:'mastered'},history:[{mode:'保留成绩',count:45,score:80}],settings:{quickEntryMigration:'quick-entry-migrated-v2.2.9-fengshen-r3',homeShortcuts:['history','mastery','sequence','search'],quickEntryCustomized:true,allModesOpen:true}}),before=json(x.t.getStore());
assert(x.main.innerHTML.includes('id="luluHomeButton"'));assert(x.main.innerHTML.includes('hero-caption'));const all=x.main.innerHTML.match(/<details class="more-modes[\s\S]*?<\/details>/)[0];assert(!all.includes('学习记录'));assert(!all.includes('507题掌握地图'));assert.deepEqual(json(x.t.getStore().settings.homeShortcuts),['history','mastery','sequence','search'],'原来自定义快捷项不得删除');
x.w.openLuluRoom();assert(x.main.innerHTML.includes('噜噜的学习小屋'));for(const t of ['学习记录','507题掌握地图'])assert(x.main.innerHTML.includes(t));assert.deepEqual(json(x.t.getStore()),before);x.w.openLuluPage('history');assert(x.main.innerHTML.includes('保留成绩'));assert.deepEqual(json(x.t.getStore()),before);x.w.openLuluRoom();x.w.openLuluPage('mastery');assert.equal((x.main.innerHTML.match(/class="mastery-cell"/g)||[]).length,507);assert.deepEqual(json(x.t.getStore()),before);x.w.navHome(true);assert(x.t.getStore().settings.allModesOpen);
x.w.beginRealExam();const session=x.t.getSession(),snapshot=json(x.t.getStore().lastSession);x.w.openLuluRoom();assert.equal(x.t.getSession(),session);assert.deepEqual(json(x.t.getStore().lastSession),snapshot,'不得丢失正在进行的考试');
// Speech lifecycle with a deterministic clock, independently of real time.
let timers=new Map(),serial=0,events={},connected=true;const bubble={textContent:'',quiet:true,classList:{add(){bubble.quiet=true},remove(){bubble.quiet=false}}},doc={hidden:false,querySelector:s=>s==='#luluSpeech'?bubble:s==='#luluHomeButton'?{isConnected:connected}:null,addEventListener:(k,f)=>events[k]=f},ctx={window:{},document:doc,setTimeout:(fn,ms)=>{let id=++serial;timers.set(id,{fn,ms});return id},clearTimeout:id=>timers.delete(id),Math};vm.createContext(ctx);vm.runInContext(fs.readFileSync('lulu.js','utf8'),ctx);ctx.window.LULU.mount();assert(bubble.textContent.includes('点击我'));assert.equal(timers.size,2);const [hideId,hide]=[...timers].find(([,t])=>t.ms===6500);timers.delete(hideId);hide.fn();assert(bubble.quiet);let [scheduledId,scheduled]=[...timers].find(([,t])=>t.ms>=22000);assert(scheduled.ms<=36000);timers.delete(scheduledId);scheduled.fn();assert(ctx.window.LULU.LINES.includes(bubble.textContent));ctx.window.LULU.stop();assert(bubble.quiet);doc.hidden=true;events.visibilitychange();assert.equal(timers.size,0);doc.hidden=false;connected=false;events.visibilitychange();assert.equal(timers.size,0);connected=true;events.visibilitychange();assert.equal(timers.size,2);ctx.window.LULU.stop();assert.equal(timers.size,0);
for(let i=0,last='';i<100;i++){let next=ctx.window.LULU.nextLine();assert.notEqual(next,last);last=next}
const image=fs.readFileSync('lulu-mascot.png');assert(image.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])));assert([4,6].includes(image[25]),'头像必须含透明通道');for(const f of ['lulu.js','lulu-mascot.png']){assert(fs.readFileSync('sw.js','utf8').includes(f));assert(fs.readFileSync('scripts/build-release.mjs','utf8').includes(f))}assert(fs.readFileSync('styles.css','utf8').includes('prefers-reduced-motion'));assert(!fs.readFileSync('lulu.js','utf8').includes('fetch('));console.log('噜噜校验通过：透明头像/主标题布局/两入口移位/自定义快捷项与所有记录保留/考试保护/随机不连说/离开首页与后台停说/离线资源/减少动态支持。');
