const assert=require('assert/strict'),zlib=require('zlib'),fs=require('fs');
const {boot}=require('./scripts/test-app-harness.cjs'),json=v=>JSON.parse(JSON.stringify(v));
function setup(seed={}){const x=boot(seed);Object.assign(x.c,{TextEncoder,TextDecoder,Uint8Array,Blob,CompressionStream,DecompressionStream,btoa,atob});x.c.FileReader=function(){this.readAsText=file=>{this.result=file.text;this.onload()}};return x;}
const now=Date.now(),source={favorites:[171,179],mastery:{171:'mastered'},reviewFlags:{179:now},seen:{171:now,179:now},wrong:{171:{count:0,wrongTotal:4,lastWrong:now-1000,lastCorrect:now+1000,corrected:true,recentResult:'independentCorrect',independentCorrectStreak:2}},learning:{171:{attempts:12,correct:10,wrong:2,last:now+1000,due:now+86400000,streak:5,fillExposure:7,totalMs:10000}}};
const target={favorites:[12,171],mastery:{12:'fuzzy',171:'fuzzy'},reviewFlags:{12:now},seen:{12:now,171:now-1000},wrong:{171:{count:1,wrongTotal:6,lastWrong:now-500,lastCorrect:0,corrected:false,recentResult:'wrong'}},learning:{171:{attempts:20,correct:17,wrong:3,totalMs:20000,last:now,due:now,streak:1,fillExposure:5}},history:[{mode:'保留考试',count:45,score:80}],aggregateStats:{totalExams:3,totalAnswers:100,totalCorrect:90},easterEggs:{discovered:['score100'],currentTitle:'初窥门径'}};
(async()=>{
const a=setup(source),b=setup(target),M=a.w.QBANK_TRANSFER,data=M.makeLite(a.t.getStore(),now);
assert.equal(data.learning[171].attempts,12);assert(!('history' in data));assert(!('aggregateStats' in data));assert(!('lastPresentation' in data.wrong[171]));
let gz,raw;for(const compatible of [false,true]){const code=await M.encode(data,compatible),decoded=await M.decode(code);assert.deepEqual(json(decoded),json(data));assert.deepEqual(json(await M.decode(' \n'+code.replace(/(.{80})/g,'$1\n')+' \n')),json(data));if(compatible)raw=code;else gz=code;}
assert(gz.startsWith('SLQ1.G.'));assert(raw.startsWith('SLQ1.C.'));assert(raw.length<JSON.stringify(data).length*1.34);
const merged=M.merge(b.t.getStore(),data);assert.deepEqual(json(merged.favorites),[12,171,179]);assert.equal(merged.mastery[171],'mastered');assert.equal(merged.mastery[12],'fuzzy');assert.equal(merged.wrong[171].count,0);assert.equal(merged.wrong[171].wrongTotal,6);assert.equal(merged.learning[171].attempts,20);assert.equal(merged.learning[171].correct,17);assert.equal(merged.learning[171].wrong,3);assert.equal(merged.learning[171].last,now+1000);assert.equal(merged.learning[171].fillExposure,7);assert.equal(merged.seen[171],now);
for(const key of ['history','aggregateStats','settings','lastSession','easterEggs','examRotation'])assert.deepEqual(json(merged[key]),json(b.t.getStore()[key]),key+' changed');
assert.deepEqual(json(M.merge(merged,data)),json(merged),'重复合并不得再增次数');assert.deepEqual(json(M.merge(merged,{...data,favorites:[]})).favorites,[12,171,179],'合并不能移除本机收藏');
const replaced=M.merge(b.t.getStore(),data,'replace');assert.deepEqual(json(replaced.favorites),[171,179]);assert(!replaced.mastery[12]);assert(!replaced.reviewFlags[12]);assert.deepEqual(json(replaced.history),json(b.t.getStore().history));
for(const code of ['',raw.slice(0,-8),raw.replace('SLQ1.','SLQ9.'),raw.slice(0,-1)+(raw.endsWith('0')?'1':'0'),'SLQ1.R.A.00000000','x'.repeat(M.MAX_CODE*2+1)])await assert.rejects(()=>M.decode(code));
for(const change of [{version:99},{bankSchemaVersion:99},{favorites:[1]},{favorites:[171,171]},{mastery:{'__proto__':'mastered',999:'new'}},{learning:{171:{last:-1}}}])await assert.rejects(()=>M.encode({...data,...change}));
const bomb=zlib.gzipSync(Buffer.alloc(600*1024,65));await assert.rejects(()=>M.decode('SLQ1.G.'+bomb.toString('base64url')+'.00000000'),/过大/);
await assert.rejects(()=>M.encode({...data,mastery:{'0171':'mastered'}}),/题号/);
assert.deepEqual(json(M.merge(b.t.getStore(),{...data,learning:{171:{...data.learning[171],last:now}}}).learning[171]).last,now,'同时间保留本机状态');
const old=setup(source);old.c.CompressionStream=undefined;old.c.DecompressionStream=undefined;assert((await old.w.QBANK_TRANSFER.encode(data)).startsWith('SLQ1.R.'));assert.deepEqual(json(await old.w.QBANK_TRANSFER.decode(raw)),json(data));await assert.rejects(()=>old.w.QBANK_TRANSFER.decode(gz),/兼容码/);
// Transactional UI import, automatic full backup and undo, not just pure merging.
b.w.openTransfer();b.nodes['#transferInput'].value=gz;await b.w.previewTransferCode();assert.equal(b.nodes['#transferApply'].disabled,false);assert(b.nodes['#transferPreview'].textContent.includes('收藏 2 题'));const before=json(b.t.getStore());b.w.applyTransferCode();assert.deepEqual(json(b.t.getStore().favorites),[12,171,179]);assert(b.store.shenrenliu_qbank_v1_before_transfer_v1);assert.deepEqual(json(b.t.unpackStore(JSON.parse(b.store.shenrenliu_qbank_v1_before_transfer_v1))),before);b.w.undoTransferCode();assert.deepEqual(json(b.t.getStore()),before);
const failure=setup(target);failure.w.openTransfer();failure.nodes['#transferInput'].value=gz;await failure.w.previewTransferCode();const failedBefore=json(failure.t.getStore()),storedBefore=failure.store.shenrenliu_qbank_v1;failure.c.localStorage.setItem=()=>{throw Error('QuotaExceeded')};failure.w.applyTransferCode();assert.deepEqual(json(failure.t.getStore()),failedBefore);assert.equal(failure.store.shenrenliu_qbank_v1,storedBefore);assert(failure.nodes['#transferStatus'].textContent.includes('未改变'));
const primaryFailure=setup(target);primaryFailure.w.openTransfer();primaryFailure.nodes['#transferInput'].value=gz;await primaryFailure.w.previewTransferCode();const set=primaryFailure.c.localStorage.setItem;primaryFailure.c.localStorage.setItem=(key,value)=>{if(key==='shenrenliu_qbank_v1')throw Error('QuotaExceeded');set(key,value)};const unchanged=json(primaryFailure.t.getStore());primaryFailure.w.applyTransferCode();assert.deepEqual(json(primaryFailure.t.getStore()),unchanged);
const invalid=setup(target);invalid.w.openTransfer();invalid.nodes['#transferInput'].value='wrong';await invalid.w.previewTransferCode();assert(invalid.nodes['#transferApply'].disabled);assert(!invalid.store.shenrenliu_qbank_v1_before_transfer_v1);
const cancel=setup(target);cancel.w.openTransfer();cancel.nodes['#transferInput'].value=gz;await cancel.w.previewTransferCode();cancel.nodes['#transferMode'].value='replace';cancel.c.confirm=()=>false;const noChange=json(cancel.t.getStore());cancel.w.applyTransferCode();assert.deepEqual(json(cancel.t.getStore()),noChange);assert(!cancel.store.shenrenliu_qbank_v1_before_transfer_v1);
const fileImport=setup(target),fileBefore=json(fileImport.t.getStore());fileImport.w.importData({text:JSON.stringify({schemaVersion:2,favorites:[179]})});assert.deepEqual(json(fileImport.t.getStore().favorites),[179]);fileImport.w.undoTransferCode();assert.deepEqual(json(fileImport.t.getStore()),fileBefore);
const fileCancel=setup(target);fileCancel.c.confirm=()=>false;const fileCancelBefore=json(fileCancel.t.getStore());fileCancel.w.importData({text:JSON.stringify({favorites:[179]})});assert.deepEqual(json(fileCancel.t.getStore()),fileCancelBefore);
const full=setup();for(const q of full.w.QUESTION_BANK){full.t.getStore().favorites.push(q.id);full.t.getStore().learning[q.id]={attempts:100,correct:80,wrong:20,totalMs:500000,last:now,due:now+86400000,fillExposure:32};}const fullCode=await full.w.QBANK_TRANSFER.encode(full.w.QBANK_TRANSFER.makeLite(full.t.getStore()),true);assert.equal(full.w.QBANK_TRANSFER.preview(await full.w.QBANK_TRANSFER.decode(fullCode)).progress,507);
assert(fs.readFileSync('scripts/build-release.mjs','utf8').includes('transfer-code.js'));assert(fs.readFileSync('sw.js','utf8').includes('transfer-code.js'));assert(fs.readFileSync('index.html','utf8').indexOf('src="transfer-code.js"')<fs.readFileSync('index.html','utf8').indexOf('src="app.js'));
console.log(JSON.stringify({transfer:'gzip/紧凑兼容码/旧浏览器/换行/损坏/超限/解压上限',merge:'幂等/不累加/时间冲突/标签/覆盖范围/原图状态',safety:'自动完整备份/撤销/存储失败零变更/覆盖取消/完整文件确认与恢复',sampleCodeLength:gz.length,all507CodeLength:fullCode.length,cloudRequests:0}));
})().catch(e=>{console.error(e);process.exitCode=1});
